
/* SCRIPT GENERATED BY POWER ARCHITECT */

ALTER TABLE feature_ms2_event DROP CONSTRAINT raw_map_feature_ms2_event_fk;

ALTER TABLE scan_sequence ALTER COLUMN raw_file_name RENAME TO raw_file_identifier;

ALTER TABLE feature_ms2_event ALTER COLUMN run_map_id RENAME TO raw_map_id;

ALTER TABLE feature ADD COLUMN peakel_count INTEGER NOT NULL;

ALTER TABLE feature_peakel_item ADD COLUMN is_base_peakel BOOLEAN NOT NULL;
ALTER INDEX feature_moz_time_charge_idx RENAME TO feature_charge_time_moz_idx;

CREATE INDEX object_tree_schema_name_idx
 ON object_tree
 ( schema_name );

CREATE INDEX peakel_time_moz_idx
 ON peakel
 ( elution_time, moz );

ALTER TABLE feature_ms2_event ADD CONSTRAINT raw_map_feature_ms2_event_fk
FOREIGN KEY (raw_map_id)
REFERENCES raw_map (id)
ON DELETE CASCADE
ON UPDATE NO ACTION;

/* END OF SCRIPT GENERATED BY POWER ARCHITECT */