/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package fr.proline.core.om.model.msi.serializer;  
@SuppressWarnings("all")
public class MsQueryProperties extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MsQueryProperties\",\"namespace\":\"fr.proline.core.om.model.msi.serializer\",\"fields\":[{\"name\":\"target_db_search\",\"default\":{},\"type\":{\"type\":\"record\",\"name\":\"MsQueryDbSearchProperties\",\"fields\":[{\"name\":\"candidate_peptides_count\",\"type\":\"int\",\"default\":-1},{\"name\":\"mascot_identity_threshold\",\"type\":\"float\",\"default\":-1.0},{\"name\":\"mascot_homology_threshold\",\"type\":\"float\",\"default\":-1}]}},{\"name\":\"decoy_db_search\",\"type\":\"MsQueryDbSearchProperties\",\"default\":{}}]}");
  @Deprecated public fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties target_db_search;
  @Deprecated public fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties decoy_db_search;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return target_db_search;
    case 1: return decoy_db_search;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: target_db_search = (fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties)value$; break;
    case 1: decoy_db_search = (fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'target_db_search' field.
   */
  public fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties getTargetDbSearch() {
    return target_db_search;
  }

  /**
   * Sets the value of the 'target_db_search' field.
   * @param value the value to set.
   */
  public void setTargetDbSearch(fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties value) {
    this.target_db_search = value;
  }

  /**
   * Gets the value of the 'decoy_db_search' field.
   */
  public fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties getDecoyDbSearch() {
    return decoy_db_search;
  }

  /**
   * Sets the value of the 'decoy_db_search' field.
   * @param value the value to set.
   */
  public void setDecoyDbSearch(fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties value) {
    this.decoy_db_search = value;
  }

  /** Creates a new MsQueryProperties RecordBuilder */
  public static fr.proline.core.om.model.msi.serializer.MsQueryProperties.Builder newBuilder() {
    return new fr.proline.core.om.model.msi.serializer.MsQueryProperties.Builder();
  }
  
  /** Creates a new MsQueryProperties RecordBuilder by copying an existing Builder */
  public static fr.proline.core.om.model.msi.serializer.MsQueryProperties.Builder newBuilder(fr.proline.core.om.model.msi.serializer.MsQueryProperties.Builder other) {
    return new fr.proline.core.om.model.msi.serializer.MsQueryProperties.Builder(other);
  }
  
  /** Creates a new MsQueryProperties RecordBuilder by copying an existing MsQueryProperties instance */
  public static fr.proline.core.om.model.msi.serializer.MsQueryProperties.Builder newBuilder(fr.proline.core.om.model.msi.serializer.MsQueryProperties other) {
    return new fr.proline.core.om.model.msi.serializer.MsQueryProperties.Builder(other);
  }
  
  /**
   * RecordBuilder for MsQueryProperties instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MsQueryProperties>
    implements org.apache.avro.data.RecordBuilder<MsQueryProperties> {

    private fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties target_db_search;
    private fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties decoy_db_search;

    /** Creates a new Builder */
    private Builder() {
      super(fr.proline.core.om.model.msi.serializer.MsQueryProperties.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(fr.proline.core.om.model.msi.serializer.MsQueryProperties.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing MsQueryProperties instance */
    private Builder(fr.proline.core.om.model.msi.serializer.MsQueryProperties other) {
            super(fr.proline.core.om.model.msi.serializer.MsQueryProperties.SCHEMA$);
      if (isValidValue(fields()[0], other.target_db_search)) {
        this.target_db_search = (fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties) data().deepCopy(fields()[0].schema(), other.target_db_search);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.decoy_db_search)) {
        this.decoy_db_search = (fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties) data().deepCopy(fields()[1].schema(), other.decoy_db_search);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'target_db_search' field */
    public fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties getTargetDbSearch() {
      return target_db_search;
    }
    
    /** Sets the value of the 'target_db_search' field */
    public fr.proline.core.om.model.msi.serializer.MsQueryProperties.Builder setTargetDbSearch(fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties value) {
      validate(fields()[0], value);
      this.target_db_search = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'target_db_search' field has been set */
    public boolean hasTargetDbSearch() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'target_db_search' field */
    public fr.proline.core.om.model.msi.serializer.MsQueryProperties.Builder clearTargetDbSearch() {
      target_db_search = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'decoy_db_search' field */
    public fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties getDecoyDbSearch() {
      return decoy_db_search;
    }
    
    /** Sets the value of the 'decoy_db_search' field */
    public fr.proline.core.om.model.msi.serializer.MsQueryProperties.Builder setDecoyDbSearch(fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties value) {
      validate(fields()[1], value);
      this.decoy_db_search = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'decoy_db_search' field has been set */
    public boolean hasDecoyDbSearch() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'decoy_db_search' field */
    public fr.proline.core.om.model.msi.serializer.MsQueryProperties.Builder clearDecoyDbSearch() {
      decoy_db_search = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public MsQueryProperties build() {
      try {
        MsQueryProperties record = new MsQueryProperties();
        record.target_db_search = fieldSetFlags()[0] ? this.target_db_search : (fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties) defaultValue(fields()[0]);
        record.decoy_db_search = fieldSetFlags()[1] ? this.decoy_db_search : (fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
