/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package fr.proline.core.om.model.msi.serializer;  
@SuppressWarnings("all")
public class MsQueryDbSearchProperties extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MsQueryDbSearchProperties\",\"namespace\":\"fr.proline.core.om.model.msi.serializer\",\"fields\":[{\"name\":\"candidate_peptides_count\",\"type\":\"int\",\"default\":\"\"},{\"name\":\"mascot_identity_threshold\",\"type\":[\"float\",\"null\"]},{\"name\":\"mascot_homology_threshold\",\"type\":[\"float\",\"null\"]}]}");
  @Deprecated public int candidate_peptides_count;
  @Deprecated public java.lang.Float mascot_identity_threshold;
  @Deprecated public java.lang.Float mascot_homology_threshold;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return candidate_peptides_count;
    case 1: return mascot_identity_threshold;
    case 2: return mascot_homology_threshold;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: candidate_peptides_count = (java.lang.Integer)value$; break;
    case 1: mascot_identity_threshold = (java.lang.Float)value$; break;
    case 2: mascot_homology_threshold = (java.lang.Float)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'candidate_peptides_count' field.
   */
  public java.lang.Integer getCandidatePeptidesCount() {
    return candidate_peptides_count;
  }

  /**
   * Sets the value of the 'candidate_peptides_count' field.
   * @param value the value to set.
   */
  public void setCandidatePeptidesCount(java.lang.Integer value) {
    this.candidate_peptides_count = value;
  }

  /**
   * Gets the value of the 'mascot_identity_threshold' field.
   */
  public java.lang.Float getMascotIdentityThreshold() {
    return mascot_identity_threshold;
  }

  /**
   * Sets the value of the 'mascot_identity_threshold' field.
   * @param value the value to set.
   */
  public void setMascotIdentityThreshold(java.lang.Float value) {
    this.mascot_identity_threshold = value;
  }

  /**
   * Gets the value of the 'mascot_homology_threshold' field.
   */
  public java.lang.Float getMascotHomologyThreshold() {
    return mascot_homology_threshold;
  }

  /**
   * Sets the value of the 'mascot_homology_threshold' field.
   * @param value the value to set.
   */
  public void setMascotHomologyThreshold(java.lang.Float value) {
    this.mascot_homology_threshold = value;
  }

  /** Creates a new MsQueryDbSearchProperties RecordBuilder */
  public static fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties.Builder newBuilder() {
    return new fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties.Builder();
  }
  
  /** Creates a new MsQueryDbSearchProperties RecordBuilder by copying an existing Builder */
  public static fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties.Builder newBuilder(fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties.Builder other) {
    return new fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties.Builder(other);
  }
  
  /** Creates a new MsQueryDbSearchProperties RecordBuilder by copying an existing MsQueryDbSearchProperties instance */
  public static fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties.Builder newBuilder(fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties other) {
    return new fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties.Builder(other);
  }
  
  /**
   * RecordBuilder for MsQueryDbSearchProperties instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MsQueryDbSearchProperties>
    implements org.apache.avro.data.RecordBuilder<MsQueryDbSearchProperties> {

    private int candidate_peptides_count;
    private java.lang.Float mascot_identity_threshold;
    private java.lang.Float mascot_homology_threshold;

    /** Creates a new Builder */
    private Builder() {
      super(fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing MsQueryDbSearchProperties instance */
    private Builder(fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties other) {
            super(fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties.SCHEMA$);
      if (isValidValue(fields()[0], other.candidate_peptides_count)) {
        this.candidate_peptides_count = (java.lang.Integer) data().deepCopy(fields()[0].schema(), other.candidate_peptides_count);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.mascot_identity_threshold)) {
        this.mascot_identity_threshold = (java.lang.Float) data().deepCopy(fields()[1].schema(), other.mascot_identity_threshold);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.mascot_homology_threshold)) {
        this.mascot_homology_threshold = (java.lang.Float) data().deepCopy(fields()[2].schema(), other.mascot_homology_threshold);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'candidate_peptides_count' field */
    public java.lang.Integer getCandidatePeptidesCount() {
      return candidate_peptides_count;
    }
    
    /** Sets the value of the 'candidate_peptides_count' field */
    public fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties.Builder setCandidatePeptidesCount(int value) {
      validate(fields()[0], value);
      this.candidate_peptides_count = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'candidate_peptides_count' field has been set */
    public boolean hasCandidatePeptidesCount() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'candidate_peptides_count' field */
    public fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties.Builder clearCandidatePeptidesCount() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'mascot_identity_threshold' field */
    public java.lang.Float getMascotIdentityThreshold() {
      return mascot_identity_threshold;
    }
    
    /** Sets the value of the 'mascot_identity_threshold' field */
    public fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties.Builder setMascotIdentityThreshold(java.lang.Float value) {
      validate(fields()[1], value);
      this.mascot_identity_threshold = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'mascot_identity_threshold' field has been set */
    public boolean hasMascotIdentityThreshold() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'mascot_identity_threshold' field */
    public fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties.Builder clearMascotIdentityThreshold() {
      mascot_identity_threshold = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'mascot_homology_threshold' field */
    public java.lang.Float getMascotHomologyThreshold() {
      return mascot_homology_threshold;
    }
    
    /** Sets the value of the 'mascot_homology_threshold' field */
    public fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties.Builder setMascotHomologyThreshold(java.lang.Float value) {
      validate(fields()[2], value);
      this.mascot_homology_threshold = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'mascot_homology_threshold' field has been set */
    public boolean hasMascotHomologyThreshold() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'mascot_homology_threshold' field */
    public fr.proline.core.om.model.msi.serializer.MsQueryDbSearchProperties.Builder clearMascotHomologyThreshold() {
      mascot_homology_threshold = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public MsQueryDbSearchProperties build() {
      try {
        MsQueryDbSearchProperties record = new MsQueryDbSearchProperties();
        record.candidate_peptides_count = fieldSetFlags()[0] ? this.candidate_peptides_count : (java.lang.Integer) defaultValue(fields()[0]);
        record.mascot_identity_threshold = fieldSetFlags()[1] ? this.mascot_identity_threshold : (java.lang.Float) defaultValue(fields()[1]);
        record.mascot_homology_threshold = fieldSetFlags()[2] ? this.mascot_homology_threshold : (java.lang.Float) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
