/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package fr.proline.core.om.model.msi.serializer;  
@SuppressWarnings("all")
public class MsQuery extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MsQuery\",\"namespace\":\"fr.proline.core.om.model.msi.serializer\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"initial_id\",\"type\":\"int\"},{\"name\":\"moz\",\"type\":\"double\"},{\"name\":\"charge\",\"type\":\"int\"},{\"name\":\"ms_level\",\"type\":\"int\"},{\"name\":\"spectrum_title\",\"type\":\"string\"},{\"name\":\"spectrum_id\",\"type\":\"int\"},{\"name\":\"properties\",\"type\":{\"type\":\"record\",\"name\":\"MsQueryProperties\",\"fields\":[{\"name\":\"target_db_search\",\"type\":{\"type\":\"record\",\"name\":\"MsQueryDbSearchProperties\",\"fields\":[{\"name\":\"candidate_peptides_count\",\"type\":\"int\",\"default\":\"\"},{\"name\":\"mascot_identity_threshold\",\"type\":\"float\"},{\"name\":\"mascot_homology_threshold\",\"type\":\"float\"}]}},{\"name\":\"decoy_db_search\",\"type\":\"MsQueryDbSearchProperties\"}]}}]}");
  @Deprecated public int id;
  @Deprecated public int initial_id;
  @Deprecated public double moz;
  @Deprecated public int charge;
  @Deprecated public int ms_level;
  @Deprecated public java.lang.CharSequence spectrum_title;
  @Deprecated public int spectrum_id;
  @Deprecated public fr.proline.core.om.model.msi.serializer.MsQueryProperties properties;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return initial_id;
    case 2: return moz;
    case 3: return charge;
    case 4: return ms_level;
    case 5: return spectrum_title;
    case 6: return spectrum_id;
    case 7: return properties;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: initial_id = (java.lang.Integer)value$; break;
    case 2: moz = (java.lang.Double)value$; break;
    case 3: charge = (java.lang.Integer)value$; break;
    case 4: ms_level = (java.lang.Integer)value$; break;
    case 5: spectrum_title = (java.lang.CharSequence)value$; break;
    case 6: spectrum_id = (java.lang.Integer)value$; break;
    case 7: properties = (fr.proline.core.om.model.msi.serializer.MsQueryProperties)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'initial_id' field.
   */
  public java.lang.Integer getInitialId() {
    return initial_id;
  }

  /**
   * Sets the value of the 'initial_id' field.
   * @param value the value to set.
   */
  public void setInitialId(java.lang.Integer value) {
    this.initial_id = value;
  }

  /**
   * Gets the value of the 'moz' field.
   */
  public java.lang.Double getMoz() {
    return moz;
  }

  /**
   * Sets the value of the 'moz' field.
   * @param value the value to set.
   */
  public void setMoz(java.lang.Double value) {
    this.moz = value;
  }

  /**
   * Gets the value of the 'charge' field.
   */
  public java.lang.Integer getCharge() {
    return charge;
  }

  /**
   * Sets the value of the 'charge' field.
   * @param value the value to set.
   */
  public void setCharge(java.lang.Integer value) {
    this.charge = value;
  }

  /**
   * Gets the value of the 'ms_level' field.
   */
  public java.lang.Integer getMsLevel() {
    return ms_level;
  }

  /**
   * Sets the value of the 'ms_level' field.
   * @param value the value to set.
   */
  public void setMsLevel(java.lang.Integer value) {
    this.ms_level = value;
  }

  /**
   * Gets the value of the 'spectrum_title' field.
   */
  public java.lang.CharSequence getSpectrumTitle() {
    return spectrum_title;
  }

  /**
   * Sets the value of the 'spectrum_title' field.
   * @param value the value to set.
   */
  public void setSpectrumTitle(java.lang.CharSequence value) {
    this.spectrum_title = value;
  }

  /**
   * Gets the value of the 'spectrum_id' field.
   */
  public java.lang.Integer getSpectrumId() {
    return spectrum_id;
  }

  /**
   * Sets the value of the 'spectrum_id' field.
   * @param value the value to set.
   */
  public void setSpectrumId(java.lang.Integer value) {
    this.spectrum_id = value;
  }

  /**
   * Gets the value of the 'properties' field.
   */
  public fr.proline.core.om.model.msi.serializer.MsQueryProperties getProperties() {
    return properties;
  }

  /**
   * Sets the value of the 'properties' field.
   * @param value the value to set.
   */
  public void setProperties(fr.proline.core.om.model.msi.serializer.MsQueryProperties value) {
    this.properties = value;
  }

  /** Creates a new MsQuery RecordBuilder */
  public static fr.proline.core.om.model.msi.serializer.MsQuery.Builder newBuilder() {
    return new fr.proline.core.om.model.msi.serializer.MsQuery.Builder();
  }
  
  /** Creates a new MsQuery RecordBuilder by copying an existing Builder */
  public static fr.proline.core.om.model.msi.serializer.MsQuery.Builder newBuilder(fr.proline.core.om.model.msi.serializer.MsQuery.Builder other) {
    return new fr.proline.core.om.model.msi.serializer.MsQuery.Builder(other);
  }
  
  /** Creates a new MsQuery RecordBuilder by copying an existing MsQuery instance */
  public static fr.proline.core.om.model.msi.serializer.MsQuery.Builder newBuilder(fr.proline.core.om.model.msi.serializer.MsQuery other) {
    return new fr.proline.core.om.model.msi.serializer.MsQuery.Builder(other);
  }
  
  /**
   * RecordBuilder for MsQuery instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MsQuery>
    implements org.apache.avro.data.RecordBuilder<MsQuery> {

    private int id;
    private int initial_id;
    private double moz;
    private int charge;
    private int ms_level;
    private java.lang.CharSequence spectrum_title;
    private int spectrum_id;
    private fr.proline.core.om.model.msi.serializer.MsQueryProperties properties;

    /** Creates a new Builder */
    private Builder() {
      super(fr.proline.core.om.model.msi.serializer.MsQuery.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(fr.proline.core.om.model.msi.serializer.MsQuery.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing MsQuery instance */
    private Builder(fr.proline.core.om.model.msi.serializer.MsQuery other) {
            super(fr.proline.core.om.model.msi.serializer.MsQuery.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = (java.lang.Integer) data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.initial_id)) {
        this.initial_id = (java.lang.Integer) data().deepCopy(fields()[1].schema(), other.initial_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.moz)) {
        this.moz = (java.lang.Double) data().deepCopy(fields()[2].schema(), other.moz);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.charge)) {
        this.charge = (java.lang.Integer) data().deepCopy(fields()[3].schema(), other.charge);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.ms_level)) {
        this.ms_level = (java.lang.Integer) data().deepCopy(fields()[4].schema(), other.ms_level);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.spectrum_title)) {
        this.spectrum_title = (java.lang.CharSequence) data().deepCopy(fields()[5].schema(), other.spectrum_title);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.spectrum_id)) {
        this.spectrum_id = (java.lang.Integer) data().deepCopy(fields()[6].schema(), other.spectrum_id);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.properties)) {
        this.properties = (fr.proline.core.om.model.msi.serializer.MsQueryProperties) data().deepCopy(fields()[7].schema(), other.properties);
        fieldSetFlags()[7] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.Integer getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public fr.proline.core.om.model.msi.serializer.MsQuery.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public fr.proline.core.om.model.msi.serializer.MsQuery.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'initial_id' field */
    public java.lang.Integer getInitialId() {
      return initial_id;
    }
    
    /** Sets the value of the 'initial_id' field */
    public fr.proline.core.om.model.msi.serializer.MsQuery.Builder setInitialId(int value) {
      validate(fields()[1], value);
      this.initial_id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'initial_id' field has been set */
    public boolean hasInitialId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'initial_id' field */
    public fr.proline.core.om.model.msi.serializer.MsQuery.Builder clearInitialId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'moz' field */
    public java.lang.Double getMoz() {
      return moz;
    }
    
    /** Sets the value of the 'moz' field */
    public fr.proline.core.om.model.msi.serializer.MsQuery.Builder setMoz(double value) {
      validate(fields()[2], value);
      this.moz = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'moz' field has been set */
    public boolean hasMoz() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'moz' field */
    public fr.proline.core.om.model.msi.serializer.MsQuery.Builder clearMoz() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'charge' field */
    public java.lang.Integer getCharge() {
      return charge;
    }
    
    /** Sets the value of the 'charge' field */
    public fr.proline.core.om.model.msi.serializer.MsQuery.Builder setCharge(int value) {
      validate(fields()[3], value);
      this.charge = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'charge' field has been set */
    public boolean hasCharge() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'charge' field */
    public fr.proline.core.om.model.msi.serializer.MsQuery.Builder clearCharge() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'ms_level' field */
    public java.lang.Integer getMsLevel() {
      return ms_level;
    }
    
    /** Sets the value of the 'ms_level' field */
    public fr.proline.core.om.model.msi.serializer.MsQuery.Builder setMsLevel(int value) {
      validate(fields()[4], value);
      this.ms_level = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'ms_level' field has been set */
    public boolean hasMsLevel() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'ms_level' field */
    public fr.proline.core.om.model.msi.serializer.MsQuery.Builder clearMsLevel() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'spectrum_title' field */
    public java.lang.CharSequence getSpectrumTitle() {
      return spectrum_title;
    }
    
    /** Sets the value of the 'spectrum_title' field */
    public fr.proline.core.om.model.msi.serializer.MsQuery.Builder setSpectrumTitle(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.spectrum_title = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'spectrum_title' field has been set */
    public boolean hasSpectrumTitle() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'spectrum_title' field */
    public fr.proline.core.om.model.msi.serializer.MsQuery.Builder clearSpectrumTitle() {
      spectrum_title = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'spectrum_id' field */
    public java.lang.Integer getSpectrumId() {
      return spectrum_id;
    }
    
    /** Sets the value of the 'spectrum_id' field */
    public fr.proline.core.om.model.msi.serializer.MsQuery.Builder setSpectrumId(int value) {
      validate(fields()[6], value);
      this.spectrum_id = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'spectrum_id' field has been set */
    public boolean hasSpectrumId() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'spectrum_id' field */
    public fr.proline.core.om.model.msi.serializer.MsQuery.Builder clearSpectrumId() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'properties' field */
    public fr.proline.core.om.model.msi.serializer.MsQueryProperties getProperties() {
      return properties;
    }
    
    /** Sets the value of the 'properties' field */
    public fr.proline.core.om.model.msi.serializer.MsQuery.Builder setProperties(fr.proline.core.om.model.msi.serializer.MsQueryProperties value) {
      validate(fields()[7], value);
      this.properties = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'properties' field has been set */
    public boolean hasProperties() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'properties' field */
    public fr.proline.core.om.model.msi.serializer.MsQuery.Builder clearProperties() {
      properties = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    public MsQuery build() {
      try {
        MsQuery record = new MsQuery();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.initial_id = fieldSetFlags()[1] ? this.initial_id : (java.lang.Integer) defaultValue(fields()[1]);
        record.moz = fieldSetFlags()[2] ? this.moz : (java.lang.Double) defaultValue(fields()[2]);
        record.charge = fieldSetFlags()[3] ? this.charge : (java.lang.Integer) defaultValue(fields()[3]);
        record.ms_level = fieldSetFlags()[4] ? this.ms_level : (java.lang.Integer) defaultValue(fields()[4]);
        record.spectrum_title = fieldSetFlags()[5] ? this.spectrum_title : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.spectrum_id = fieldSetFlags()[6] ? this.spectrum_id : (java.lang.Integer) defaultValue(fields()[6]);
        record.properties = fieldSetFlags()[7] ? this.properties : (fr.proline.core.om.model.msi.serializer.MsQueryProperties) defaultValue(fields()[7]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
