/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package fr.proline.core.om.model.msi.serializer;  
@SuppressWarnings("all")
public class Peaklist extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Peaklist\",\"namespace\":\"fr.proline.core.om.model.msi.serializer\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"path\",\"type\":\"string\"},{\"name\":\"raw_file_name\",\"type\":\"string\"},{\"name\":\"ms_level\",\"type\":\"int\"},{\"name\":\"properties\",\"type\":{\"type\":\"record\",\"name\":\"PeaklistProperties\",\"fields\":[{\"name\":\"spectrum_data_compression_level\",\"type\":[\"int\",\"null\"]}]}},{\"name\":\"peaklist_software\",\"type\":{\"type\":\"record\",\"name\":\"PeaklistSoftware\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"}]}}]}");
  @Deprecated public int id;
  @Deprecated public java.lang.CharSequence type;
  @Deprecated public java.lang.CharSequence path;
  @Deprecated public java.lang.CharSequence raw_file_name;
  @Deprecated public int ms_level;
  @Deprecated public fr.proline.core.om.model.msi.serializer.PeaklistProperties properties;
  @Deprecated public fr.proline.core.om.model.msi.serializer.PeaklistSoftware peaklist_software;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return type;
    case 2: return path;
    case 3: return raw_file_name;
    case 4: return ms_level;
    case 5: return properties;
    case 6: return peaklist_software;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: type = (java.lang.CharSequence)value$; break;
    case 2: path = (java.lang.CharSequence)value$; break;
    case 3: raw_file_name = (java.lang.CharSequence)value$; break;
    case 4: ms_level = (java.lang.Integer)value$; break;
    case 5: properties = (fr.proline.core.om.model.msi.serializer.PeaklistProperties)value$; break;
    case 6: peaklist_software = (fr.proline.core.om.model.msi.serializer.PeaklistSoftware)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'type' field.
   */
  public java.lang.CharSequence getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.CharSequence value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'path' field.
   */
  public java.lang.CharSequence getPath() {
    return path;
  }

  /**
   * Sets the value of the 'path' field.
   * @param value the value to set.
   */
  public void setPath(java.lang.CharSequence value) {
    this.path = value;
  }

  /**
   * Gets the value of the 'raw_file_name' field.
   */
  public java.lang.CharSequence getRawFileName() {
    return raw_file_name;
  }

  /**
   * Sets the value of the 'raw_file_name' field.
   * @param value the value to set.
   */
  public void setRawFileName(java.lang.CharSequence value) {
    this.raw_file_name = value;
  }

  /**
   * Gets the value of the 'ms_level' field.
   */
  public java.lang.Integer getMsLevel() {
    return ms_level;
  }

  /**
   * Sets the value of the 'ms_level' field.
   * @param value the value to set.
   */
  public void setMsLevel(java.lang.Integer value) {
    this.ms_level = value;
  }

  /**
   * Gets the value of the 'properties' field.
   */
  public fr.proline.core.om.model.msi.serializer.PeaklistProperties getProperties() {
    return properties;
  }

  /**
   * Sets the value of the 'properties' field.
   * @param value the value to set.
   */
  public void setProperties(fr.proline.core.om.model.msi.serializer.PeaklistProperties value) {
    this.properties = value;
  }

  /**
   * Gets the value of the 'peaklist_software' field.
   */
  public fr.proline.core.om.model.msi.serializer.PeaklistSoftware getPeaklistSoftware() {
    return peaklist_software;
  }

  /**
   * Sets the value of the 'peaklist_software' field.
   * @param value the value to set.
   */
  public void setPeaklistSoftware(fr.proline.core.om.model.msi.serializer.PeaklistSoftware value) {
    this.peaklist_software = value;
  }

  /** Creates a new Peaklist RecordBuilder */
  public static fr.proline.core.om.model.msi.serializer.Peaklist.Builder newBuilder() {
    return new fr.proline.core.om.model.msi.serializer.Peaklist.Builder();
  }
  
  /** Creates a new Peaklist RecordBuilder by copying an existing Builder */
  public static fr.proline.core.om.model.msi.serializer.Peaklist.Builder newBuilder(fr.proline.core.om.model.msi.serializer.Peaklist.Builder other) {
    return new fr.proline.core.om.model.msi.serializer.Peaklist.Builder(other);
  }
  
  /** Creates a new Peaklist RecordBuilder by copying an existing Peaklist instance */
  public static fr.proline.core.om.model.msi.serializer.Peaklist.Builder newBuilder(fr.proline.core.om.model.msi.serializer.Peaklist other) {
    return new fr.proline.core.om.model.msi.serializer.Peaklist.Builder(other);
  }
  
  /**
   * RecordBuilder for Peaklist instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Peaklist>
    implements org.apache.avro.data.RecordBuilder<Peaklist> {

    private int id;
    private java.lang.CharSequence type;
    private java.lang.CharSequence path;
    private java.lang.CharSequence raw_file_name;
    private int ms_level;
    private fr.proline.core.om.model.msi.serializer.PeaklistProperties properties;
    private fr.proline.core.om.model.msi.serializer.PeaklistSoftware peaklist_software;

    /** Creates a new Builder */
    private Builder() {
      super(fr.proline.core.om.model.msi.serializer.Peaklist.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(fr.proline.core.om.model.msi.serializer.Peaklist.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Peaklist instance */
    private Builder(fr.proline.core.om.model.msi.serializer.Peaklist other) {
            super(fr.proline.core.om.model.msi.serializer.Peaklist.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = (java.lang.Integer) data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = (java.lang.CharSequence) data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.path)) {
        this.path = (java.lang.CharSequence) data().deepCopy(fields()[2].schema(), other.path);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.raw_file_name)) {
        this.raw_file_name = (java.lang.CharSequence) data().deepCopy(fields()[3].schema(), other.raw_file_name);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.ms_level)) {
        this.ms_level = (java.lang.Integer) data().deepCopy(fields()[4].schema(), other.ms_level);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.properties)) {
        this.properties = (fr.proline.core.om.model.msi.serializer.PeaklistProperties) data().deepCopy(fields()[5].schema(), other.properties);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.peaklist_software)) {
        this.peaklist_software = (fr.proline.core.om.model.msi.serializer.PeaklistSoftware) data().deepCopy(fields()[6].schema(), other.peaklist_software);
        fieldSetFlags()[6] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.Integer getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public fr.proline.core.om.model.msi.serializer.Peaklist.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public fr.proline.core.om.model.msi.serializer.Peaklist.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'type' field */
    public java.lang.CharSequence getType() {
      return type;
    }
    
    /** Sets the value of the 'type' field */
    public fr.proline.core.om.model.msi.serializer.Peaklist.Builder setType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.type = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'type' field has been set */
    public boolean hasType() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'type' field */
    public fr.proline.core.om.model.msi.serializer.Peaklist.Builder clearType() {
      type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'path' field */
    public java.lang.CharSequence getPath() {
      return path;
    }
    
    /** Sets the value of the 'path' field */
    public fr.proline.core.om.model.msi.serializer.Peaklist.Builder setPath(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.path = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'path' field has been set */
    public boolean hasPath() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'path' field */
    public fr.proline.core.om.model.msi.serializer.Peaklist.Builder clearPath() {
      path = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'raw_file_name' field */
    public java.lang.CharSequence getRawFileName() {
      return raw_file_name;
    }
    
    /** Sets the value of the 'raw_file_name' field */
    public fr.proline.core.om.model.msi.serializer.Peaklist.Builder setRawFileName(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.raw_file_name = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'raw_file_name' field has been set */
    public boolean hasRawFileName() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'raw_file_name' field */
    public fr.proline.core.om.model.msi.serializer.Peaklist.Builder clearRawFileName() {
      raw_file_name = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'ms_level' field */
    public java.lang.Integer getMsLevel() {
      return ms_level;
    }
    
    /** Sets the value of the 'ms_level' field */
    public fr.proline.core.om.model.msi.serializer.Peaklist.Builder setMsLevel(int value) {
      validate(fields()[4], value);
      this.ms_level = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'ms_level' field has been set */
    public boolean hasMsLevel() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'ms_level' field */
    public fr.proline.core.om.model.msi.serializer.Peaklist.Builder clearMsLevel() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'properties' field */
    public fr.proline.core.om.model.msi.serializer.PeaklistProperties getProperties() {
      return properties;
    }
    
    /** Sets the value of the 'properties' field */
    public fr.proline.core.om.model.msi.serializer.Peaklist.Builder setProperties(fr.proline.core.om.model.msi.serializer.PeaklistProperties value) {
      validate(fields()[5], value);
      this.properties = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'properties' field has been set */
    public boolean hasProperties() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'properties' field */
    public fr.proline.core.om.model.msi.serializer.Peaklist.Builder clearProperties() {
      properties = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'peaklist_software' field */
    public fr.proline.core.om.model.msi.serializer.PeaklistSoftware getPeaklistSoftware() {
      return peaklist_software;
    }
    
    /** Sets the value of the 'peaklist_software' field */
    public fr.proline.core.om.model.msi.serializer.Peaklist.Builder setPeaklistSoftware(fr.proline.core.om.model.msi.serializer.PeaklistSoftware value) {
      validate(fields()[6], value);
      this.peaklist_software = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'peaklist_software' field has been set */
    public boolean hasPeaklistSoftware() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'peaklist_software' field */
    public fr.proline.core.om.model.msi.serializer.Peaklist.Builder clearPeaklistSoftware() {
      peaklist_software = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    public Peaklist build() {
      try {
        Peaklist record = new Peaklist();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.type = fieldSetFlags()[1] ? this.type : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.path = fieldSetFlags()[2] ? this.path : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.raw_file_name = fieldSetFlags()[3] ? this.raw_file_name : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.ms_level = fieldSetFlags()[4] ? this.ms_level : (java.lang.Integer) defaultValue(fields()[4]);
        record.properties = fieldSetFlags()[5] ? this.properties : (fr.proline.core.om.model.msi.serializer.PeaklistProperties) defaultValue(fields()[5]);
        record.peaklist_software = fieldSetFlags()[6] ? this.peaklist_software : (fr.proline.core.om.model.msi.serializer.PeaklistSoftware) defaultValue(fields()[6]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
