/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package fr.proline.core.om.model.msi.serializer;  
@SuppressWarnings("all")
public class PeptideSetItem extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PeptideSetItem\",\"namespace\":\"fr.proline.core.om.model.msi.serializer\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"is_best_peptide_set\",\"type\":\"boolean\"},{\"name\":\"selection_level\",\"type\":\"int\"},{\"name\":\"peptide_instance\",\"type\":{\"type\":\"record\",\"name\":\"PeptideInstance\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"peptide_matches_count\",\"type\":\"int\"},{\"name\":\"protein_matches_count\",\"type\":\"int\"},{\"name\":\"protein_sets_count\",\"type\":\"int\"},{\"name\":\"selection_level\",\"type\":\"int\"},{\"name\":\"properties\",\"type\":{\"type\":\"record\",\"name\":\"PeptideInstanceProperties\",\"fields\":[]}},{\"name\":\"peptide\",\"type\":{\"type\":\"record\",\"name\":\"Peptide\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"sequence\",\"type\":\"string\"},{\"name\":\"ptm_string\",\"type\":\"string\"},{\"name\":\"calculated_mass\",\"type\":\"double\"},{\"name\":\"ptms\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}},{\"name\":\"unmodified_peptide_id\",\"type\":\"int\"},{\"name\":\"peptide_match_ids\",\"type\":{\"type\":\"array\",\"items\":\"int\"}},{\"name\":\"peptide_match_properties_by_id\",\"type\":{\"type\":\"map\",\"values\":\"string\"}},{\"name\":\"best_peptide_match_id\",\"type\":\"int\"},{\"name\":\"result_summary_id\",\"type\":\"int\"}]}},{\"name\":\"peptide_set_id\",\"type\":\"int\"}]}");
  @Deprecated public int id;
  @Deprecated public boolean is_best_peptide_set;
  @Deprecated public int selection_level;
  @Deprecated public fr.proline.core.om.model.msi.serializer.PeptideInstance peptide_instance;
  @Deprecated public int peptide_set_id;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return is_best_peptide_set;
    case 2: return selection_level;
    case 3: return peptide_instance;
    case 4: return peptide_set_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: is_best_peptide_set = (java.lang.Boolean)value$; break;
    case 2: selection_level = (java.lang.Integer)value$; break;
    case 3: peptide_instance = (fr.proline.core.om.model.msi.serializer.PeptideInstance)value$; break;
    case 4: peptide_set_id = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'is_best_peptide_set' field.
   */
  public java.lang.Boolean getIsBestPeptideSet() {
    return is_best_peptide_set;
  }

  /**
   * Sets the value of the 'is_best_peptide_set' field.
   * @param value the value to set.
   */
  public void setIsBestPeptideSet(java.lang.Boolean value) {
    this.is_best_peptide_set = value;
  }

  /**
   * Gets the value of the 'selection_level' field.
   */
  public java.lang.Integer getSelectionLevel() {
    return selection_level;
  }

  /**
   * Sets the value of the 'selection_level' field.
   * @param value the value to set.
   */
  public void setSelectionLevel(java.lang.Integer value) {
    this.selection_level = value;
  }

  /**
   * Gets the value of the 'peptide_instance' field.
   */
  public fr.proline.core.om.model.msi.serializer.PeptideInstance getPeptideInstance() {
    return peptide_instance;
  }

  /**
   * Sets the value of the 'peptide_instance' field.
   * @param value the value to set.
   */
  public void setPeptideInstance(fr.proline.core.om.model.msi.serializer.PeptideInstance value) {
    this.peptide_instance = value;
  }

  /**
   * Gets the value of the 'peptide_set_id' field.
   */
  public java.lang.Integer getPeptideSetId() {
    return peptide_set_id;
  }

  /**
   * Sets the value of the 'peptide_set_id' field.
   * @param value the value to set.
   */
  public void setPeptideSetId(java.lang.Integer value) {
    this.peptide_set_id = value;
  }

  /** Creates a new PeptideSetItem RecordBuilder */
  public static fr.proline.core.om.model.msi.serializer.PeptideSetItem.Builder newBuilder() {
    return new fr.proline.core.om.model.msi.serializer.PeptideSetItem.Builder();
  }
  
  /** Creates a new PeptideSetItem RecordBuilder by copying an existing Builder */
  public static fr.proline.core.om.model.msi.serializer.PeptideSetItem.Builder newBuilder(fr.proline.core.om.model.msi.serializer.PeptideSetItem.Builder other) {
    return new fr.proline.core.om.model.msi.serializer.PeptideSetItem.Builder(other);
  }
  
  /** Creates a new PeptideSetItem RecordBuilder by copying an existing PeptideSetItem instance */
  public static fr.proline.core.om.model.msi.serializer.PeptideSetItem.Builder newBuilder(fr.proline.core.om.model.msi.serializer.PeptideSetItem other) {
    return new fr.proline.core.om.model.msi.serializer.PeptideSetItem.Builder(other);
  }
  
  /**
   * RecordBuilder for PeptideSetItem instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PeptideSetItem>
    implements org.apache.avro.data.RecordBuilder<PeptideSetItem> {

    private int id;
    private boolean is_best_peptide_set;
    private int selection_level;
    private fr.proline.core.om.model.msi.serializer.PeptideInstance peptide_instance;
    private int peptide_set_id;

    /** Creates a new Builder */
    private Builder() {
      super(fr.proline.core.om.model.msi.serializer.PeptideSetItem.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(fr.proline.core.om.model.msi.serializer.PeptideSetItem.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing PeptideSetItem instance */
    private Builder(fr.proline.core.om.model.msi.serializer.PeptideSetItem other) {
            super(fr.proline.core.om.model.msi.serializer.PeptideSetItem.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = (java.lang.Integer) data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.is_best_peptide_set)) {
        this.is_best_peptide_set = (java.lang.Boolean) data().deepCopy(fields()[1].schema(), other.is_best_peptide_set);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.selection_level)) {
        this.selection_level = (java.lang.Integer) data().deepCopy(fields()[2].schema(), other.selection_level);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.peptide_instance)) {
        this.peptide_instance = (fr.proline.core.om.model.msi.serializer.PeptideInstance) data().deepCopy(fields()[3].schema(), other.peptide_instance);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.peptide_set_id)) {
        this.peptide_set_id = (java.lang.Integer) data().deepCopy(fields()[4].schema(), other.peptide_set_id);
        fieldSetFlags()[4] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.Integer getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public fr.proline.core.om.model.msi.serializer.PeptideSetItem.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public fr.proline.core.om.model.msi.serializer.PeptideSetItem.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'is_best_peptide_set' field */
    public java.lang.Boolean getIsBestPeptideSet() {
      return is_best_peptide_set;
    }
    
    /** Sets the value of the 'is_best_peptide_set' field */
    public fr.proline.core.om.model.msi.serializer.PeptideSetItem.Builder setIsBestPeptideSet(boolean value) {
      validate(fields()[1], value);
      this.is_best_peptide_set = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'is_best_peptide_set' field has been set */
    public boolean hasIsBestPeptideSet() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'is_best_peptide_set' field */
    public fr.proline.core.om.model.msi.serializer.PeptideSetItem.Builder clearIsBestPeptideSet() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'selection_level' field */
    public java.lang.Integer getSelectionLevel() {
      return selection_level;
    }
    
    /** Sets the value of the 'selection_level' field */
    public fr.proline.core.om.model.msi.serializer.PeptideSetItem.Builder setSelectionLevel(int value) {
      validate(fields()[2], value);
      this.selection_level = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'selection_level' field has been set */
    public boolean hasSelectionLevel() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'selection_level' field */
    public fr.proline.core.om.model.msi.serializer.PeptideSetItem.Builder clearSelectionLevel() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'peptide_instance' field */
    public fr.proline.core.om.model.msi.serializer.PeptideInstance getPeptideInstance() {
      return peptide_instance;
    }
    
    /** Sets the value of the 'peptide_instance' field */
    public fr.proline.core.om.model.msi.serializer.PeptideSetItem.Builder setPeptideInstance(fr.proline.core.om.model.msi.serializer.PeptideInstance value) {
      validate(fields()[3], value);
      this.peptide_instance = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'peptide_instance' field has been set */
    public boolean hasPeptideInstance() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'peptide_instance' field */
    public fr.proline.core.om.model.msi.serializer.PeptideSetItem.Builder clearPeptideInstance() {
      peptide_instance = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'peptide_set_id' field */
    public java.lang.Integer getPeptideSetId() {
      return peptide_set_id;
    }
    
    /** Sets the value of the 'peptide_set_id' field */
    public fr.proline.core.om.model.msi.serializer.PeptideSetItem.Builder setPeptideSetId(int value) {
      validate(fields()[4], value);
      this.peptide_set_id = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'peptide_set_id' field has been set */
    public boolean hasPeptideSetId() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'peptide_set_id' field */
    public fr.proline.core.om.model.msi.serializer.PeptideSetItem.Builder clearPeptideSetId() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public PeptideSetItem build() {
      try {
        PeptideSetItem record = new PeptideSetItem();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.is_best_peptide_set = fieldSetFlags()[1] ? this.is_best_peptide_set : (java.lang.Boolean) defaultValue(fields()[1]);
        record.selection_level = fieldSetFlags()[2] ? this.selection_level : (java.lang.Integer) defaultValue(fields()[2]);
        record.peptide_instance = fieldSetFlags()[3] ? this.peptide_instance : (fr.proline.core.om.model.msi.serializer.PeptideInstance) defaultValue(fields()[3]);
        record.peptide_set_id = fieldSetFlags()[4] ? this.peptide_set_id : (java.lang.Integer) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
