/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package fr.proline.core.om.model.msi.serializer;  
@SuppressWarnings("all")
public class PeptideInstance extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PeptideInstance\",\"namespace\":\"fr.proline.core.om.model.msi.serializer\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"peptide_matches_count\",\"type\":\"int\"},{\"name\":\"protein_matches_count\",\"type\":\"int\"},{\"name\":\"protein_sets_count\",\"type\":\"int\"},{\"name\":\"selection_level\",\"type\":\"int\"},{\"name\":\"properties\",\"type\":{\"type\":\"record\",\"name\":\"PeptideInstanceProperties\",\"fields\":[]}},{\"name\":\"peptide\",\"type\":{\"type\":\"record\",\"name\":\"Peptide\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"sequence\",\"type\":\"string\"},{\"name\":\"ptm_string\",\"type\":\"string\"},{\"name\":\"calculated_mass\",\"type\":\"double\"},{\"name\":\"ptms\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}},{\"name\":\"unmodified_peptide_id\",\"type\":\"int\"},{\"name\":\"peptide_match_ids\",\"type\":{\"type\":\"array\",\"items\":\"int\"}},{\"name\":\"peptide_match_properties_by_id\",\"type\":{\"type\":\"map\",\"values\":\"string\"}},{\"name\":\"best_peptide_match_id\",\"type\":\"int\"},{\"name\":\"result_summary_id\",\"type\":\"int\"}]}");
  @Deprecated public int id;
  @Deprecated public int peptide_matches_count;
  @Deprecated public int protein_matches_count;
  @Deprecated public int protein_sets_count;
  @Deprecated public int selection_level;
  @Deprecated public fr.proline.core.om.model.msi.serializer.PeptideInstanceProperties properties;
  @Deprecated public fr.proline.core.om.model.msi.serializer.Peptide peptide;
  @Deprecated public int unmodified_peptide_id;
  @Deprecated public java.util.List<java.lang.Integer> peptide_match_ids;
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> peptide_match_properties_by_id;
  @Deprecated public int best_peptide_match_id;
  @Deprecated public int result_summary_id;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return peptide_matches_count;
    case 2: return protein_matches_count;
    case 3: return protein_sets_count;
    case 4: return selection_level;
    case 5: return properties;
    case 6: return peptide;
    case 7: return unmodified_peptide_id;
    case 8: return peptide_match_ids;
    case 9: return peptide_match_properties_by_id;
    case 10: return best_peptide_match_id;
    case 11: return result_summary_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: peptide_matches_count = (java.lang.Integer)value$; break;
    case 2: protein_matches_count = (java.lang.Integer)value$; break;
    case 3: protein_sets_count = (java.lang.Integer)value$; break;
    case 4: selection_level = (java.lang.Integer)value$; break;
    case 5: properties = (fr.proline.core.om.model.msi.serializer.PeptideInstanceProperties)value$; break;
    case 6: peptide = (fr.proline.core.om.model.msi.serializer.Peptide)value$; break;
    case 7: unmodified_peptide_id = (java.lang.Integer)value$; break;
    case 8: peptide_match_ids = (java.util.List<java.lang.Integer>)value$; break;
    case 9: peptide_match_properties_by_id = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    case 10: best_peptide_match_id = (java.lang.Integer)value$; break;
    case 11: result_summary_id = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'peptide_matches_count' field.
   */
  public java.lang.Integer getPeptideMatchesCount() {
    return peptide_matches_count;
  }

  /**
   * Sets the value of the 'peptide_matches_count' field.
   * @param value the value to set.
   */
  public void setPeptideMatchesCount(java.lang.Integer value) {
    this.peptide_matches_count = value;
  }

  /**
   * Gets the value of the 'protein_matches_count' field.
   */
  public java.lang.Integer getProteinMatchesCount() {
    return protein_matches_count;
  }

  /**
   * Sets the value of the 'protein_matches_count' field.
   * @param value the value to set.
   */
  public void setProteinMatchesCount(java.lang.Integer value) {
    this.protein_matches_count = value;
  }

  /**
   * Gets the value of the 'protein_sets_count' field.
   */
  public java.lang.Integer getProteinSetsCount() {
    return protein_sets_count;
  }

  /**
   * Sets the value of the 'protein_sets_count' field.
   * @param value the value to set.
   */
  public void setProteinSetsCount(java.lang.Integer value) {
    this.protein_sets_count = value;
  }

  /**
   * Gets the value of the 'selection_level' field.
   */
  public java.lang.Integer getSelectionLevel() {
    return selection_level;
  }

  /**
   * Sets the value of the 'selection_level' field.
   * @param value the value to set.
   */
  public void setSelectionLevel(java.lang.Integer value) {
    this.selection_level = value;
  }

  /**
   * Gets the value of the 'properties' field.
   */
  public fr.proline.core.om.model.msi.serializer.PeptideInstanceProperties getProperties() {
    return properties;
  }

  /**
   * Sets the value of the 'properties' field.
   * @param value the value to set.
   */
  public void setProperties(fr.proline.core.om.model.msi.serializer.PeptideInstanceProperties value) {
    this.properties = value;
  }

  /**
   * Gets the value of the 'peptide' field.
   */
  public fr.proline.core.om.model.msi.serializer.Peptide getPeptide() {
    return peptide;
  }

  /**
   * Sets the value of the 'peptide' field.
   * @param value the value to set.
   */
  public void setPeptide(fr.proline.core.om.model.msi.serializer.Peptide value) {
    this.peptide = value;
  }

  /**
   * Gets the value of the 'unmodified_peptide_id' field.
   */
  public java.lang.Integer getUnmodifiedPeptideId() {
    return unmodified_peptide_id;
  }

  /**
   * Sets the value of the 'unmodified_peptide_id' field.
   * @param value the value to set.
   */
  public void setUnmodifiedPeptideId(java.lang.Integer value) {
    this.unmodified_peptide_id = value;
  }

  /**
   * Gets the value of the 'peptide_match_ids' field.
   */
  public java.util.List<java.lang.Integer> getPeptideMatchIds() {
    return peptide_match_ids;
  }

  /**
   * Sets the value of the 'peptide_match_ids' field.
   * @param value the value to set.
   */
  public void setPeptideMatchIds(java.util.List<java.lang.Integer> value) {
    this.peptide_match_ids = value;
  }

  /**
   * Gets the value of the 'peptide_match_properties_by_id' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getPeptideMatchPropertiesById() {
    return peptide_match_properties_by_id;
  }

  /**
   * Sets the value of the 'peptide_match_properties_by_id' field.
   * @param value the value to set.
   */
  public void setPeptideMatchPropertiesById(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.peptide_match_properties_by_id = value;
  }

  /**
   * Gets the value of the 'best_peptide_match_id' field.
   */
  public java.lang.Integer getBestPeptideMatchId() {
    return best_peptide_match_id;
  }

  /**
   * Sets the value of the 'best_peptide_match_id' field.
   * @param value the value to set.
   */
  public void setBestPeptideMatchId(java.lang.Integer value) {
    this.best_peptide_match_id = value;
  }

  /**
   * Gets the value of the 'result_summary_id' field.
   */
  public java.lang.Integer getResultSummaryId() {
    return result_summary_id;
  }

  /**
   * Sets the value of the 'result_summary_id' field.
   * @param value the value to set.
   */
  public void setResultSummaryId(java.lang.Integer value) {
    this.result_summary_id = value;
  }

  /** Creates a new PeptideInstance RecordBuilder */
  public static fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder newBuilder() {
    return new fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder();
  }
  
  /** Creates a new PeptideInstance RecordBuilder by copying an existing Builder */
  public static fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder newBuilder(fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder other) {
    return new fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder(other);
  }
  
  /** Creates a new PeptideInstance RecordBuilder by copying an existing PeptideInstance instance */
  public static fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder newBuilder(fr.proline.core.om.model.msi.serializer.PeptideInstance other) {
    return new fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder(other);
  }
  
  /**
   * RecordBuilder for PeptideInstance instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PeptideInstance>
    implements org.apache.avro.data.RecordBuilder<PeptideInstance> {

    private int id;
    private int peptide_matches_count;
    private int protein_matches_count;
    private int protein_sets_count;
    private int selection_level;
    private fr.proline.core.om.model.msi.serializer.PeptideInstanceProperties properties;
    private fr.proline.core.om.model.msi.serializer.Peptide peptide;
    private int unmodified_peptide_id;
    private java.util.List<java.lang.Integer> peptide_match_ids;
    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> peptide_match_properties_by_id;
    private int best_peptide_match_id;
    private int result_summary_id;

    /** Creates a new Builder */
    private Builder() {
      super(fr.proline.core.om.model.msi.serializer.PeptideInstance.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing PeptideInstance instance */
    private Builder(fr.proline.core.om.model.msi.serializer.PeptideInstance other) {
            super(fr.proline.core.om.model.msi.serializer.PeptideInstance.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = (java.lang.Integer) data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.peptide_matches_count)) {
        this.peptide_matches_count = (java.lang.Integer) data().deepCopy(fields()[1].schema(), other.peptide_matches_count);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.protein_matches_count)) {
        this.protein_matches_count = (java.lang.Integer) data().deepCopy(fields()[2].schema(), other.protein_matches_count);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.protein_sets_count)) {
        this.protein_sets_count = (java.lang.Integer) data().deepCopy(fields()[3].schema(), other.protein_sets_count);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.selection_level)) {
        this.selection_level = (java.lang.Integer) data().deepCopy(fields()[4].schema(), other.selection_level);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.properties)) {
        this.properties = (fr.proline.core.om.model.msi.serializer.PeptideInstanceProperties) data().deepCopy(fields()[5].schema(), other.properties);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.peptide)) {
        this.peptide = (fr.proline.core.om.model.msi.serializer.Peptide) data().deepCopy(fields()[6].schema(), other.peptide);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.unmodified_peptide_id)) {
        this.unmodified_peptide_id = (java.lang.Integer) data().deepCopy(fields()[7].schema(), other.unmodified_peptide_id);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.peptide_match_ids)) {
        this.peptide_match_ids = (java.util.List<java.lang.Integer>) data().deepCopy(fields()[8].schema(), other.peptide_match_ids);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.peptide_match_properties_by_id)) {
        this.peptide_match_properties_by_id = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) data().deepCopy(fields()[9].schema(), other.peptide_match_properties_by_id);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.best_peptide_match_id)) {
        this.best_peptide_match_id = (java.lang.Integer) data().deepCopy(fields()[10].schema(), other.best_peptide_match_id);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.result_summary_id)) {
        this.result_summary_id = (java.lang.Integer) data().deepCopy(fields()[11].schema(), other.result_summary_id);
        fieldSetFlags()[11] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.Integer getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'peptide_matches_count' field */
    public java.lang.Integer getPeptideMatchesCount() {
      return peptide_matches_count;
    }
    
    /** Sets the value of the 'peptide_matches_count' field */
    public fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder setPeptideMatchesCount(int value) {
      validate(fields()[1], value);
      this.peptide_matches_count = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'peptide_matches_count' field has been set */
    public boolean hasPeptideMatchesCount() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'peptide_matches_count' field */
    public fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder clearPeptideMatchesCount() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'protein_matches_count' field */
    public java.lang.Integer getProteinMatchesCount() {
      return protein_matches_count;
    }
    
    /** Sets the value of the 'protein_matches_count' field */
    public fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder setProteinMatchesCount(int value) {
      validate(fields()[2], value);
      this.protein_matches_count = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'protein_matches_count' field has been set */
    public boolean hasProteinMatchesCount() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'protein_matches_count' field */
    public fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder clearProteinMatchesCount() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'protein_sets_count' field */
    public java.lang.Integer getProteinSetsCount() {
      return protein_sets_count;
    }
    
    /** Sets the value of the 'protein_sets_count' field */
    public fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder setProteinSetsCount(int value) {
      validate(fields()[3], value);
      this.protein_sets_count = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'protein_sets_count' field has been set */
    public boolean hasProteinSetsCount() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'protein_sets_count' field */
    public fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder clearProteinSetsCount() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'selection_level' field */
    public java.lang.Integer getSelectionLevel() {
      return selection_level;
    }
    
    /** Sets the value of the 'selection_level' field */
    public fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder setSelectionLevel(int value) {
      validate(fields()[4], value);
      this.selection_level = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'selection_level' field has been set */
    public boolean hasSelectionLevel() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'selection_level' field */
    public fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder clearSelectionLevel() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'properties' field */
    public fr.proline.core.om.model.msi.serializer.PeptideInstanceProperties getProperties() {
      return properties;
    }
    
    /** Sets the value of the 'properties' field */
    public fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder setProperties(fr.proline.core.om.model.msi.serializer.PeptideInstanceProperties value) {
      validate(fields()[5], value);
      this.properties = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'properties' field has been set */
    public boolean hasProperties() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'properties' field */
    public fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder clearProperties() {
      properties = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'peptide' field */
    public fr.proline.core.om.model.msi.serializer.Peptide getPeptide() {
      return peptide;
    }
    
    /** Sets the value of the 'peptide' field */
    public fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder setPeptide(fr.proline.core.om.model.msi.serializer.Peptide value) {
      validate(fields()[6], value);
      this.peptide = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'peptide' field has been set */
    public boolean hasPeptide() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'peptide' field */
    public fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder clearPeptide() {
      peptide = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'unmodified_peptide_id' field */
    public java.lang.Integer getUnmodifiedPeptideId() {
      return unmodified_peptide_id;
    }
    
    /** Sets the value of the 'unmodified_peptide_id' field */
    public fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder setUnmodifiedPeptideId(int value) {
      validate(fields()[7], value);
      this.unmodified_peptide_id = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'unmodified_peptide_id' field has been set */
    public boolean hasUnmodifiedPeptideId() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'unmodified_peptide_id' field */
    public fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder clearUnmodifiedPeptideId() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'peptide_match_ids' field */
    public java.util.List<java.lang.Integer> getPeptideMatchIds() {
      return peptide_match_ids;
    }
    
    /** Sets the value of the 'peptide_match_ids' field */
    public fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder setPeptideMatchIds(java.util.List<java.lang.Integer> value) {
      validate(fields()[8], value);
      this.peptide_match_ids = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'peptide_match_ids' field has been set */
    public boolean hasPeptideMatchIds() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'peptide_match_ids' field */
    public fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder clearPeptideMatchIds() {
      peptide_match_ids = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'peptide_match_properties_by_id' field */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getPeptideMatchPropertiesById() {
      return peptide_match_properties_by_id;
    }
    
    /** Sets the value of the 'peptide_match_properties_by_id' field */
    public fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder setPeptideMatchPropertiesById(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[9], value);
      this.peptide_match_properties_by_id = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'peptide_match_properties_by_id' field has been set */
    public boolean hasPeptideMatchPropertiesById() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'peptide_match_properties_by_id' field */
    public fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder clearPeptideMatchPropertiesById() {
      peptide_match_properties_by_id = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'best_peptide_match_id' field */
    public java.lang.Integer getBestPeptideMatchId() {
      return best_peptide_match_id;
    }
    
    /** Sets the value of the 'best_peptide_match_id' field */
    public fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder setBestPeptideMatchId(int value) {
      validate(fields()[10], value);
      this.best_peptide_match_id = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'best_peptide_match_id' field has been set */
    public boolean hasBestPeptideMatchId() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'best_peptide_match_id' field */
    public fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder clearBestPeptideMatchId() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'result_summary_id' field */
    public java.lang.Integer getResultSummaryId() {
      return result_summary_id;
    }
    
    /** Sets the value of the 'result_summary_id' field */
    public fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder setResultSummaryId(int value) {
      validate(fields()[11], value);
      this.result_summary_id = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'result_summary_id' field has been set */
    public boolean hasResultSummaryId() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'result_summary_id' field */
    public fr.proline.core.om.model.msi.serializer.PeptideInstance.Builder clearResultSummaryId() {
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    public PeptideInstance build() {
      try {
        PeptideInstance record = new PeptideInstance();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.peptide_matches_count = fieldSetFlags()[1] ? this.peptide_matches_count : (java.lang.Integer) defaultValue(fields()[1]);
        record.protein_matches_count = fieldSetFlags()[2] ? this.protein_matches_count : (java.lang.Integer) defaultValue(fields()[2]);
        record.protein_sets_count = fieldSetFlags()[3] ? this.protein_sets_count : (java.lang.Integer) defaultValue(fields()[3]);
        record.selection_level = fieldSetFlags()[4] ? this.selection_level : (java.lang.Integer) defaultValue(fields()[4]);
        record.properties = fieldSetFlags()[5] ? this.properties : (fr.proline.core.om.model.msi.serializer.PeptideInstanceProperties) defaultValue(fields()[5]);
        record.peptide = fieldSetFlags()[6] ? this.peptide : (fr.proline.core.om.model.msi.serializer.Peptide) defaultValue(fields()[6]);
        record.unmodified_peptide_id = fieldSetFlags()[7] ? this.unmodified_peptide_id : (java.lang.Integer) defaultValue(fields()[7]);
        record.peptide_match_ids = fieldSetFlags()[8] ? this.peptide_match_ids : (java.util.List<java.lang.Integer>) defaultValue(fields()[8]);
        record.peptide_match_properties_by_id = fieldSetFlags()[9] ? this.peptide_match_properties_by_id : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[9]);
        record.best_peptide_match_id = fieldSetFlags()[10] ? this.best_peptide_match_id : (java.lang.Integer) defaultValue(fields()[10]);
        record.result_summary_id = fieldSetFlags()[11] ? this.result_summary_id : (java.lang.Integer) defaultValue(fields()[11]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
