/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package fr.proline.core.om.model.msi.serializer;  
@SuppressWarnings("all")
public class ProteinMatch extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProteinMatch\",\"namespace\":\"fr.proline.core.om.model.msi.serializer\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"accession\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"gene_name\",\"type\":\"string\"},{\"name\":\"score\",\"type\":\"float\"},{\"name\":\"score_type\",\"type\":\"string\"},{\"name\":\"coverage\",\"type\":\"float\"},{\"name\":\"peptide_matches_count\",\"type\":\"int\"},{\"name\":\"properties\",\"type\":{\"type\":\"record\",\"name\":\"ProteinMatchProperties\",\"fields\":[]}},{\"name\":\"sequence_matches\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"taxon_id\",\"type\":\"int\"},{\"name\":\"protein_id\",\"type\":\"int\"},{\"name\":\"result_set_id\",\"type\":\"int\"}]}");
  @Deprecated public int id;
  @Deprecated public java.lang.CharSequence accession;
  @Deprecated public java.lang.CharSequence description;
  @Deprecated public java.lang.CharSequence gene_name;
  @Deprecated public float score;
  @Deprecated public java.lang.CharSequence score_type;
  @Deprecated public float coverage;
  @Deprecated public int peptide_matches_count;
  @Deprecated public fr.proline.core.om.model.msi.serializer.ProteinMatchProperties properties;
  @Deprecated public java.util.List<java.lang.CharSequence> sequence_matches;
  @Deprecated public int taxon_id;
  @Deprecated public int protein_id;
  @Deprecated public int result_set_id;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return accession;
    case 2: return description;
    case 3: return gene_name;
    case 4: return score;
    case 5: return score_type;
    case 6: return coverage;
    case 7: return peptide_matches_count;
    case 8: return properties;
    case 9: return sequence_matches;
    case 10: return taxon_id;
    case 11: return protein_id;
    case 12: return result_set_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: accession = (java.lang.CharSequence)value$; break;
    case 2: description = (java.lang.CharSequence)value$; break;
    case 3: gene_name = (java.lang.CharSequence)value$; break;
    case 4: score = (java.lang.Float)value$; break;
    case 5: score_type = (java.lang.CharSequence)value$; break;
    case 6: coverage = (java.lang.Float)value$; break;
    case 7: peptide_matches_count = (java.lang.Integer)value$; break;
    case 8: properties = (fr.proline.core.om.model.msi.serializer.ProteinMatchProperties)value$; break;
    case 9: sequence_matches = (java.util.List<java.lang.CharSequence>)value$; break;
    case 10: taxon_id = (java.lang.Integer)value$; break;
    case 11: protein_id = (java.lang.Integer)value$; break;
    case 12: result_set_id = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'accession' field.
   */
  public java.lang.CharSequence getAccession() {
    return accession;
  }

  /**
   * Sets the value of the 'accession' field.
   * @param value the value to set.
   */
  public void setAccession(java.lang.CharSequence value) {
    this.accession = value;
  }

  /**
   * Gets the value of the 'description' field.
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }

  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'gene_name' field.
   */
  public java.lang.CharSequence getGeneName() {
    return gene_name;
  }

  /**
   * Sets the value of the 'gene_name' field.
   * @param value the value to set.
   */
  public void setGeneName(java.lang.CharSequence value) {
    this.gene_name = value;
  }

  /**
   * Gets the value of the 'score' field.
   */
  public java.lang.Float getScore() {
    return score;
  }

  /**
   * Sets the value of the 'score' field.
   * @param value the value to set.
   */
  public void setScore(java.lang.Float value) {
    this.score = value;
  }

  /**
   * Gets the value of the 'score_type' field.
   */
  public java.lang.CharSequence getScoreType() {
    return score_type;
  }

  /**
   * Sets the value of the 'score_type' field.
   * @param value the value to set.
   */
  public void setScoreType(java.lang.CharSequence value) {
    this.score_type = value;
  }

  /**
   * Gets the value of the 'coverage' field.
   */
  public java.lang.Float getCoverage() {
    return coverage;
  }

  /**
   * Sets the value of the 'coverage' field.
   * @param value the value to set.
   */
  public void setCoverage(java.lang.Float value) {
    this.coverage = value;
  }

  /**
   * Gets the value of the 'peptide_matches_count' field.
   */
  public java.lang.Integer getPeptideMatchesCount() {
    return peptide_matches_count;
  }

  /**
   * Sets the value of the 'peptide_matches_count' field.
   * @param value the value to set.
   */
  public void setPeptideMatchesCount(java.lang.Integer value) {
    this.peptide_matches_count = value;
  }

  /**
   * Gets the value of the 'properties' field.
   */
  public fr.proline.core.om.model.msi.serializer.ProteinMatchProperties getProperties() {
    return properties;
  }

  /**
   * Sets the value of the 'properties' field.
   * @param value the value to set.
   */
  public void setProperties(fr.proline.core.om.model.msi.serializer.ProteinMatchProperties value) {
    this.properties = value;
  }

  /**
   * Gets the value of the 'sequence_matches' field.
   */
  public java.util.List<java.lang.CharSequence> getSequenceMatches() {
    return sequence_matches;
  }

  /**
   * Sets the value of the 'sequence_matches' field.
   * @param value the value to set.
   */
  public void setSequenceMatches(java.util.List<java.lang.CharSequence> value) {
    this.sequence_matches = value;
  }

  /**
   * Gets the value of the 'taxon_id' field.
   */
  public java.lang.Integer getTaxonId() {
    return taxon_id;
  }

  /**
   * Sets the value of the 'taxon_id' field.
   * @param value the value to set.
   */
  public void setTaxonId(java.lang.Integer value) {
    this.taxon_id = value;
  }

  /**
   * Gets the value of the 'protein_id' field.
   */
  public java.lang.Integer getProteinId() {
    return protein_id;
  }

  /**
   * Sets the value of the 'protein_id' field.
   * @param value the value to set.
   */
  public void setProteinId(java.lang.Integer value) {
    this.protein_id = value;
  }

  /**
   * Gets the value of the 'result_set_id' field.
   */
  public java.lang.Integer getResultSetId() {
    return result_set_id;
  }

  /**
   * Sets the value of the 'result_set_id' field.
   * @param value the value to set.
   */
  public void setResultSetId(java.lang.Integer value) {
    this.result_set_id = value;
  }

  /** Creates a new ProteinMatch RecordBuilder */
  public static fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder newBuilder() {
    return new fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder();
  }
  
  /** Creates a new ProteinMatch RecordBuilder by copying an existing Builder */
  public static fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder newBuilder(fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder other) {
    return new fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder(other);
  }
  
  /** Creates a new ProteinMatch RecordBuilder by copying an existing ProteinMatch instance */
  public static fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder newBuilder(fr.proline.core.om.model.msi.serializer.ProteinMatch other) {
    return new fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder(other);
  }
  
  /**
   * RecordBuilder for ProteinMatch instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProteinMatch>
    implements org.apache.avro.data.RecordBuilder<ProteinMatch> {

    private int id;
    private java.lang.CharSequence accession;
    private java.lang.CharSequence description;
    private java.lang.CharSequence gene_name;
    private float score;
    private java.lang.CharSequence score_type;
    private float coverage;
    private int peptide_matches_count;
    private fr.proline.core.om.model.msi.serializer.ProteinMatchProperties properties;
    private java.util.List<java.lang.CharSequence> sequence_matches;
    private int taxon_id;
    private int protein_id;
    private int result_set_id;

    /** Creates a new Builder */
    private Builder() {
      super(fr.proline.core.om.model.msi.serializer.ProteinMatch.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing ProteinMatch instance */
    private Builder(fr.proline.core.om.model.msi.serializer.ProteinMatch other) {
            super(fr.proline.core.om.model.msi.serializer.ProteinMatch.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = (java.lang.Integer) data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.accession)) {
        this.accession = (java.lang.CharSequence) data().deepCopy(fields()[1].schema(), other.accession);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.description)) {
        this.description = (java.lang.CharSequence) data().deepCopy(fields()[2].schema(), other.description);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.gene_name)) {
        this.gene_name = (java.lang.CharSequence) data().deepCopy(fields()[3].schema(), other.gene_name);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.score)) {
        this.score = (java.lang.Float) data().deepCopy(fields()[4].schema(), other.score);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.score_type)) {
        this.score_type = (java.lang.CharSequence) data().deepCopy(fields()[5].schema(), other.score_type);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.coverage)) {
        this.coverage = (java.lang.Float) data().deepCopy(fields()[6].schema(), other.coverage);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.peptide_matches_count)) {
        this.peptide_matches_count = (java.lang.Integer) data().deepCopy(fields()[7].schema(), other.peptide_matches_count);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.properties)) {
        this.properties = (fr.proline.core.om.model.msi.serializer.ProteinMatchProperties) data().deepCopy(fields()[8].schema(), other.properties);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.sequence_matches)) {
        this.sequence_matches = (java.util.List<java.lang.CharSequence>) data().deepCopy(fields()[9].schema(), other.sequence_matches);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.taxon_id)) {
        this.taxon_id = (java.lang.Integer) data().deepCopy(fields()[10].schema(), other.taxon_id);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.protein_id)) {
        this.protein_id = (java.lang.Integer) data().deepCopy(fields()[11].schema(), other.protein_id);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.result_set_id)) {
        this.result_set_id = (java.lang.Integer) data().deepCopy(fields()[12].schema(), other.result_set_id);
        fieldSetFlags()[12] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.Integer getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'accession' field */
    public java.lang.CharSequence getAccession() {
      return accession;
    }
    
    /** Sets the value of the 'accession' field */
    public fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder setAccession(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.accession = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'accession' field has been set */
    public boolean hasAccession() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'accession' field */
    public fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder clearAccession() {
      accession = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'description' field */
    public java.lang.CharSequence getDescription() {
      return description;
    }
    
    /** Sets the value of the 'description' field */
    public fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.description = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'description' field has been set */
    public boolean hasDescription() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'description' field */
    public fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder clearDescription() {
      description = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'gene_name' field */
    public java.lang.CharSequence getGeneName() {
      return gene_name;
    }
    
    /** Sets the value of the 'gene_name' field */
    public fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder setGeneName(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.gene_name = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'gene_name' field has been set */
    public boolean hasGeneName() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'gene_name' field */
    public fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder clearGeneName() {
      gene_name = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'score' field */
    public java.lang.Float getScore() {
      return score;
    }
    
    /** Sets the value of the 'score' field */
    public fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder setScore(float value) {
      validate(fields()[4], value);
      this.score = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'score' field has been set */
    public boolean hasScore() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'score' field */
    public fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder clearScore() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'score_type' field */
    public java.lang.CharSequence getScoreType() {
      return score_type;
    }
    
    /** Sets the value of the 'score_type' field */
    public fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder setScoreType(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.score_type = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'score_type' field has been set */
    public boolean hasScoreType() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'score_type' field */
    public fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder clearScoreType() {
      score_type = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'coverage' field */
    public java.lang.Float getCoverage() {
      return coverage;
    }
    
    /** Sets the value of the 'coverage' field */
    public fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder setCoverage(float value) {
      validate(fields()[6], value);
      this.coverage = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'coverage' field has been set */
    public boolean hasCoverage() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'coverage' field */
    public fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder clearCoverage() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'peptide_matches_count' field */
    public java.lang.Integer getPeptideMatchesCount() {
      return peptide_matches_count;
    }
    
    /** Sets the value of the 'peptide_matches_count' field */
    public fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder setPeptideMatchesCount(int value) {
      validate(fields()[7], value);
      this.peptide_matches_count = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'peptide_matches_count' field has been set */
    public boolean hasPeptideMatchesCount() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'peptide_matches_count' field */
    public fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder clearPeptideMatchesCount() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'properties' field */
    public fr.proline.core.om.model.msi.serializer.ProteinMatchProperties getProperties() {
      return properties;
    }
    
    /** Sets the value of the 'properties' field */
    public fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder setProperties(fr.proline.core.om.model.msi.serializer.ProteinMatchProperties value) {
      validate(fields()[8], value);
      this.properties = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'properties' field has been set */
    public boolean hasProperties() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'properties' field */
    public fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder clearProperties() {
      properties = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'sequence_matches' field */
    public java.util.List<java.lang.CharSequence> getSequenceMatches() {
      return sequence_matches;
    }
    
    /** Sets the value of the 'sequence_matches' field */
    public fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder setSequenceMatches(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[9], value);
      this.sequence_matches = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'sequence_matches' field has been set */
    public boolean hasSequenceMatches() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'sequence_matches' field */
    public fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder clearSequenceMatches() {
      sequence_matches = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'taxon_id' field */
    public java.lang.Integer getTaxonId() {
      return taxon_id;
    }
    
    /** Sets the value of the 'taxon_id' field */
    public fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder setTaxonId(int value) {
      validate(fields()[10], value);
      this.taxon_id = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'taxon_id' field has been set */
    public boolean hasTaxonId() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'taxon_id' field */
    public fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder clearTaxonId() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'protein_id' field */
    public java.lang.Integer getProteinId() {
      return protein_id;
    }
    
    /** Sets the value of the 'protein_id' field */
    public fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder setProteinId(int value) {
      validate(fields()[11], value);
      this.protein_id = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'protein_id' field has been set */
    public boolean hasProteinId() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'protein_id' field */
    public fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder clearProteinId() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'result_set_id' field */
    public java.lang.Integer getResultSetId() {
      return result_set_id;
    }
    
    /** Sets the value of the 'result_set_id' field */
    public fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder setResultSetId(int value) {
      validate(fields()[12], value);
      this.result_set_id = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'result_set_id' field has been set */
    public boolean hasResultSetId() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'result_set_id' field */
    public fr.proline.core.om.model.msi.serializer.ProteinMatch.Builder clearResultSetId() {
      fieldSetFlags()[12] = false;
      return this;
    }

    @Override
    public ProteinMatch build() {
      try {
        ProteinMatch record = new ProteinMatch();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.accession = fieldSetFlags()[1] ? this.accession : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.description = fieldSetFlags()[2] ? this.description : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.gene_name = fieldSetFlags()[3] ? this.gene_name : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.score = fieldSetFlags()[4] ? this.score : (java.lang.Float) defaultValue(fields()[4]);
        record.score_type = fieldSetFlags()[5] ? this.score_type : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.coverage = fieldSetFlags()[6] ? this.coverage : (java.lang.Float) defaultValue(fields()[6]);
        record.peptide_matches_count = fieldSetFlags()[7] ? this.peptide_matches_count : (java.lang.Integer) defaultValue(fields()[7]);
        record.properties = fieldSetFlags()[8] ? this.properties : (fr.proline.core.om.model.msi.serializer.ProteinMatchProperties) defaultValue(fields()[8]);
        record.sequence_matches = fieldSetFlags()[9] ? this.sequence_matches : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[9]);
        record.taxon_id = fieldSetFlags()[10] ? this.taxon_id : (java.lang.Integer) defaultValue(fields()[10]);
        record.protein_id = fieldSetFlags()[11] ? this.protein_id : (java.lang.Integer) defaultValue(fields()[11]);
        record.result_set_id = fieldSetFlags()[12] ? this.result_set_id : (java.lang.Integer) defaultValue(fields()[12]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
