/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package fr.proline.core.om.model.msi.serializer;  
@SuppressWarnings("all")
public class ProteinMatchProperties extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProteinMatchProperties\",\"namespace\":\"fr.proline.core.om.model.msi.serializer\",\"fields\":[]}");
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /** Creates a new ProteinMatchProperties RecordBuilder */
  public static fr.proline.core.om.model.msi.serializer.ProteinMatchProperties.Builder newBuilder() {
    return new fr.proline.core.om.model.msi.serializer.ProteinMatchProperties.Builder();
  }
  
  /** Creates a new ProteinMatchProperties RecordBuilder by copying an existing Builder */
  public static fr.proline.core.om.model.msi.serializer.ProteinMatchProperties.Builder newBuilder(fr.proline.core.om.model.msi.serializer.ProteinMatchProperties.Builder other) {
    return new fr.proline.core.om.model.msi.serializer.ProteinMatchProperties.Builder(other);
  }
  
  /** Creates a new ProteinMatchProperties RecordBuilder by copying an existing ProteinMatchProperties instance */
  public static fr.proline.core.om.model.msi.serializer.ProteinMatchProperties.Builder newBuilder(fr.proline.core.om.model.msi.serializer.ProteinMatchProperties other) {
    return new fr.proline.core.om.model.msi.serializer.ProteinMatchProperties.Builder(other);
  }
  
  /**
   * RecordBuilder for ProteinMatchProperties instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProteinMatchProperties>
    implements org.apache.avro.data.RecordBuilder<ProteinMatchProperties> {


    /** Creates a new Builder */
    private Builder() {
      super(fr.proline.core.om.model.msi.serializer.ProteinMatchProperties.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(fr.proline.core.om.model.msi.serializer.ProteinMatchProperties.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing ProteinMatchProperties instance */
    private Builder(fr.proline.core.om.model.msi.serializer.ProteinMatchProperties other) {
            super(fr.proline.core.om.model.msi.serializer.ProteinMatchProperties.SCHEMA$);
    }

    @Override
    public ProteinMatchProperties build() {
      try {
        ProteinMatchProperties record = new ProteinMatchProperties();
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
