/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package fr.proline.core.om.model.msi.serializer;  
@SuppressWarnings("all")
public class ResultSummaryProperties extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ResultSummaryProperties\",\"namespace\":\"fr.proline.core.om.model.msi.serializer\",\"fields\":[]}");
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /** Creates a new ResultSummaryProperties RecordBuilder */
  public static fr.proline.core.om.model.msi.serializer.ResultSummaryProperties.Builder newBuilder() {
    return new fr.proline.core.om.model.msi.serializer.ResultSummaryProperties.Builder();
  }
  
  /** Creates a new ResultSummaryProperties RecordBuilder by copying an existing Builder */
  public static fr.proline.core.om.model.msi.serializer.ResultSummaryProperties.Builder newBuilder(fr.proline.core.om.model.msi.serializer.ResultSummaryProperties.Builder other) {
    return new fr.proline.core.om.model.msi.serializer.ResultSummaryProperties.Builder(other);
  }
  
  /** Creates a new ResultSummaryProperties RecordBuilder by copying an existing ResultSummaryProperties instance */
  public static fr.proline.core.om.model.msi.serializer.ResultSummaryProperties.Builder newBuilder(fr.proline.core.om.model.msi.serializer.ResultSummaryProperties other) {
    return new fr.proline.core.om.model.msi.serializer.ResultSummaryProperties.Builder(other);
  }
  
  /**
   * RecordBuilder for ResultSummaryProperties instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ResultSummaryProperties>
    implements org.apache.avro.data.RecordBuilder<ResultSummaryProperties> {


    /** Creates a new Builder */
    private Builder() {
      super(fr.proline.core.om.model.msi.serializer.ResultSummaryProperties.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(fr.proline.core.om.model.msi.serializer.ResultSummaryProperties.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing ResultSummaryProperties instance */
    private Builder(fr.proline.core.om.model.msi.serializer.ResultSummaryProperties other) {
            super(fr.proline.core.om.model.msi.serializer.ResultSummaryProperties.SCHEMA$);
    }

    @Override
    public ResultSummaryProperties build() {
      try {
        ResultSummaryProperties record = new ResultSummaryProperties();
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
