/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package fr.proline.core.om.model.msi.serializer;  
@SuppressWarnings("all")
public class ResultSummary extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ResultSummary\",\"namespace\":\"fr.proline.core.om.model.msi.serializer\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"is_decoy\",\"type\":\"boolean\"},{\"name\":\"is_quantified\",\"type\":\"boolean\"},{\"name\":\"modification_timestamp\",\"type\":\"string\"},{\"name\":\"peptide_sets\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"protein_sets\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"properties\",\"type\":{\"type\":\"record\",\"name\":\"ResultSummaryProperties\",\"fields\":[]}},{\"name\":\"result_set_id\",\"type\":\"int\"},{\"name\":\"decoy_result_summary_id\",\"type\":\"int\"},{\"name\":\"children_ids\",\"type\":{\"type\":\"array\",\"items\":\"int\"}}]}");
  @Deprecated public int id;
  @Deprecated public java.lang.CharSequence description;
  @Deprecated public boolean is_decoy;
  @Deprecated public boolean is_quantified;
  @Deprecated public java.lang.CharSequence modification_timestamp;
  @Deprecated public java.util.List<java.lang.CharSequence> peptide_sets;
  @Deprecated public java.util.List<java.lang.CharSequence> protein_sets;
  @Deprecated public fr.proline.core.om.model.msi.serializer.ResultSummaryProperties properties;
  @Deprecated public int result_set_id;
  @Deprecated public int decoy_result_summary_id;
  @Deprecated public java.util.List<java.lang.Integer> children_ids;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return description;
    case 2: return is_decoy;
    case 3: return is_quantified;
    case 4: return modification_timestamp;
    case 5: return peptide_sets;
    case 6: return protein_sets;
    case 7: return properties;
    case 8: return result_set_id;
    case 9: return decoy_result_summary_id;
    case 10: return children_ids;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: description = (java.lang.CharSequence)value$; break;
    case 2: is_decoy = (java.lang.Boolean)value$; break;
    case 3: is_quantified = (java.lang.Boolean)value$; break;
    case 4: modification_timestamp = (java.lang.CharSequence)value$; break;
    case 5: peptide_sets = (java.util.List<java.lang.CharSequence>)value$; break;
    case 6: protein_sets = (java.util.List<java.lang.CharSequence>)value$; break;
    case 7: properties = (fr.proline.core.om.model.msi.serializer.ResultSummaryProperties)value$; break;
    case 8: result_set_id = (java.lang.Integer)value$; break;
    case 9: decoy_result_summary_id = (java.lang.Integer)value$; break;
    case 10: children_ids = (java.util.List<java.lang.Integer>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'description' field.
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }

  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'is_decoy' field.
   */
  public java.lang.Boolean getIsDecoy() {
    return is_decoy;
  }

  /**
   * Sets the value of the 'is_decoy' field.
   * @param value the value to set.
   */
  public void setIsDecoy(java.lang.Boolean value) {
    this.is_decoy = value;
  }

  /**
   * Gets the value of the 'is_quantified' field.
   */
  public java.lang.Boolean getIsQuantified() {
    return is_quantified;
  }

  /**
   * Sets the value of the 'is_quantified' field.
   * @param value the value to set.
   */
  public void setIsQuantified(java.lang.Boolean value) {
    this.is_quantified = value;
  }

  /**
   * Gets the value of the 'modification_timestamp' field.
   */
  public java.lang.CharSequence getModificationTimestamp() {
    return modification_timestamp;
  }

  /**
   * Sets the value of the 'modification_timestamp' field.
   * @param value the value to set.
   */
  public void setModificationTimestamp(java.lang.CharSequence value) {
    this.modification_timestamp = value;
  }

  /**
   * Gets the value of the 'peptide_sets' field.
   */
  public java.util.List<java.lang.CharSequence> getPeptideSets() {
    return peptide_sets;
  }

  /**
   * Sets the value of the 'peptide_sets' field.
   * @param value the value to set.
   */
  public void setPeptideSets(java.util.List<java.lang.CharSequence> value) {
    this.peptide_sets = value;
  }

  /**
   * Gets the value of the 'protein_sets' field.
   */
  public java.util.List<java.lang.CharSequence> getProteinSets() {
    return protein_sets;
  }

  /**
   * Sets the value of the 'protein_sets' field.
   * @param value the value to set.
   */
  public void setProteinSets(java.util.List<java.lang.CharSequence> value) {
    this.protein_sets = value;
  }

  /**
   * Gets the value of the 'properties' field.
   */
  public fr.proline.core.om.model.msi.serializer.ResultSummaryProperties getProperties() {
    return properties;
  }

  /**
   * Sets the value of the 'properties' field.
   * @param value the value to set.
   */
  public void setProperties(fr.proline.core.om.model.msi.serializer.ResultSummaryProperties value) {
    this.properties = value;
  }

  /**
   * Gets the value of the 'result_set_id' field.
   */
  public java.lang.Integer getResultSetId() {
    return result_set_id;
  }

  /**
   * Sets the value of the 'result_set_id' field.
   * @param value the value to set.
   */
  public void setResultSetId(java.lang.Integer value) {
    this.result_set_id = value;
  }

  /**
   * Gets the value of the 'decoy_result_summary_id' field.
   */
  public java.lang.Integer getDecoyResultSummaryId() {
    return decoy_result_summary_id;
  }

  /**
   * Sets the value of the 'decoy_result_summary_id' field.
   * @param value the value to set.
   */
  public void setDecoyResultSummaryId(java.lang.Integer value) {
    this.decoy_result_summary_id = value;
  }

  /**
   * Gets the value of the 'children_ids' field.
   */
  public java.util.List<java.lang.Integer> getChildrenIds() {
    return children_ids;
  }

  /**
   * Sets the value of the 'children_ids' field.
   * @param value the value to set.
   */
  public void setChildrenIds(java.util.List<java.lang.Integer> value) {
    this.children_ids = value;
  }

  /** Creates a new ResultSummary RecordBuilder */
  public static fr.proline.core.om.model.msi.serializer.ResultSummary.Builder newBuilder() {
    return new fr.proline.core.om.model.msi.serializer.ResultSummary.Builder();
  }
  
  /** Creates a new ResultSummary RecordBuilder by copying an existing Builder */
  public static fr.proline.core.om.model.msi.serializer.ResultSummary.Builder newBuilder(fr.proline.core.om.model.msi.serializer.ResultSummary.Builder other) {
    return new fr.proline.core.om.model.msi.serializer.ResultSummary.Builder(other);
  }
  
  /** Creates a new ResultSummary RecordBuilder by copying an existing ResultSummary instance */
  public static fr.proline.core.om.model.msi.serializer.ResultSummary.Builder newBuilder(fr.proline.core.om.model.msi.serializer.ResultSummary other) {
    return new fr.proline.core.om.model.msi.serializer.ResultSummary.Builder(other);
  }
  
  /**
   * RecordBuilder for ResultSummary instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ResultSummary>
    implements org.apache.avro.data.RecordBuilder<ResultSummary> {

    private int id;
    private java.lang.CharSequence description;
    private boolean is_decoy;
    private boolean is_quantified;
    private java.lang.CharSequence modification_timestamp;
    private java.util.List<java.lang.CharSequence> peptide_sets;
    private java.util.List<java.lang.CharSequence> protein_sets;
    private fr.proline.core.om.model.msi.serializer.ResultSummaryProperties properties;
    private int result_set_id;
    private int decoy_result_summary_id;
    private java.util.List<java.lang.Integer> children_ids;

    /** Creates a new Builder */
    private Builder() {
      super(fr.proline.core.om.model.msi.serializer.ResultSummary.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(fr.proline.core.om.model.msi.serializer.ResultSummary.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing ResultSummary instance */
    private Builder(fr.proline.core.om.model.msi.serializer.ResultSummary other) {
            super(fr.proline.core.om.model.msi.serializer.ResultSummary.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = (java.lang.Integer) data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.description)) {
        this.description = (java.lang.CharSequence) data().deepCopy(fields()[1].schema(), other.description);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.is_decoy)) {
        this.is_decoy = (java.lang.Boolean) data().deepCopy(fields()[2].schema(), other.is_decoy);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.is_quantified)) {
        this.is_quantified = (java.lang.Boolean) data().deepCopy(fields()[3].schema(), other.is_quantified);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.modification_timestamp)) {
        this.modification_timestamp = (java.lang.CharSequence) data().deepCopy(fields()[4].schema(), other.modification_timestamp);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.peptide_sets)) {
        this.peptide_sets = (java.util.List<java.lang.CharSequence>) data().deepCopy(fields()[5].schema(), other.peptide_sets);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.protein_sets)) {
        this.protein_sets = (java.util.List<java.lang.CharSequence>) data().deepCopy(fields()[6].schema(), other.protein_sets);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.properties)) {
        this.properties = (fr.proline.core.om.model.msi.serializer.ResultSummaryProperties) data().deepCopy(fields()[7].schema(), other.properties);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.result_set_id)) {
        this.result_set_id = (java.lang.Integer) data().deepCopy(fields()[8].schema(), other.result_set_id);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.decoy_result_summary_id)) {
        this.decoy_result_summary_id = (java.lang.Integer) data().deepCopy(fields()[9].schema(), other.decoy_result_summary_id);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.children_ids)) {
        this.children_ids = (java.util.List<java.lang.Integer>) data().deepCopy(fields()[10].schema(), other.children_ids);
        fieldSetFlags()[10] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.Integer getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public fr.proline.core.om.model.msi.serializer.ResultSummary.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public fr.proline.core.om.model.msi.serializer.ResultSummary.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'description' field */
    public java.lang.CharSequence getDescription() {
      return description;
    }
    
    /** Sets the value of the 'description' field */
    public fr.proline.core.om.model.msi.serializer.ResultSummary.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.description = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'description' field has been set */
    public boolean hasDescription() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'description' field */
    public fr.proline.core.om.model.msi.serializer.ResultSummary.Builder clearDescription() {
      description = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'is_decoy' field */
    public java.lang.Boolean getIsDecoy() {
      return is_decoy;
    }
    
    /** Sets the value of the 'is_decoy' field */
    public fr.proline.core.om.model.msi.serializer.ResultSummary.Builder setIsDecoy(boolean value) {
      validate(fields()[2], value);
      this.is_decoy = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'is_decoy' field has been set */
    public boolean hasIsDecoy() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'is_decoy' field */
    public fr.proline.core.om.model.msi.serializer.ResultSummary.Builder clearIsDecoy() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'is_quantified' field */
    public java.lang.Boolean getIsQuantified() {
      return is_quantified;
    }
    
    /** Sets the value of the 'is_quantified' field */
    public fr.proline.core.om.model.msi.serializer.ResultSummary.Builder setIsQuantified(boolean value) {
      validate(fields()[3], value);
      this.is_quantified = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'is_quantified' field has been set */
    public boolean hasIsQuantified() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'is_quantified' field */
    public fr.proline.core.om.model.msi.serializer.ResultSummary.Builder clearIsQuantified() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'modification_timestamp' field */
    public java.lang.CharSequence getModificationTimestamp() {
      return modification_timestamp;
    }
    
    /** Sets the value of the 'modification_timestamp' field */
    public fr.proline.core.om.model.msi.serializer.ResultSummary.Builder setModificationTimestamp(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.modification_timestamp = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'modification_timestamp' field has been set */
    public boolean hasModificationTimestamp() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'modification_timestamp' field */
    public fr.proline.core.om.model.msi.serializer.ResultSummary.Builder clearModificationTimestamp() {
      modification_timestamp = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'peptide_sets' field */
    public java.util.List<java.lang.CharSequence> getPeptideSets() {
      return peptide_sets;
    }
    
    /** Sets the value of the 'peptide_sets' field */
    public fr.proline.core.om.model.msi.serializer.ResultSummary.Builder setPeptideSets(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[5], value);
      this.peptide_sets = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'peptide_sets' field has been set */
    public boolean hasPeptideSets() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'peptide_sets' field */
    public fr.proline.core.om.model.msi.serializer.ResultSummary.Builder clearPeptideSets() {
      peptide_sets = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'protein_sets' field */
    public java.util.List<java.lang.CharSequence> getProteinSets() {
      return protein_sets;
    }
    
    /** Sets the value of the 'protein_sets' field */
    public fr.proline.core.om.model.msi.serializer.ResultSummary.Builder setProteinSets(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[6], value);
      this.protein_sets = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'protein_sets' field has been set */
    public boolean hasProteinSets() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'protein_sets' field */
    public fr.proline.core.om.model.msi.serializer.ResultSummary.Builder clearProteinSets() {
      protein_sets = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'properties' field */
    public fr.proline.core.om.model.msi.serializer.ResultSummaryProperties getProperties() {
      return properties;
    }
    
    /** Sets the value of the 'properties' field */
    public fr.proline.core.om.model.msi.serializer.ResultSummary.Builder setProperties(fr.proline.core.om.model.msi.serializer.ResultSummaryProperties value) {
      validate(fields()[7], value);
      this.properties = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'properties' field has been set */
    public boolean hasProperties() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'properties' field */
    public fr.proline.core.om.model.msi.serializer.ResultSummary.Builder clearProperties() {
      properties = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'result_set_id' field */
    public java.lang.Integer getResultSetId() {
      return result_set_id;
    }
    
    /** Sets the value of the 'result_set_id' field */
    public fr.proline.core.om.model.msi.serializer.ResultSummary.Builder setResultSetId(int value) {
      validate(fields()[8], value);
      this.result_set_id = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'result_set_id' field has been set */
    public boolean hasResultSetId() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'result_set_id' field */
    public fr.proline.core.om.model.msi.serializer.ResultSummary.Builder clearResultSetId() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'decoy_result_summary_id' field */
    public java.lang.Integer getDecoyResultSummaryId() {
      return decoy_result_summary_id;
    }
    
    /** Sets the value of the 'decoy_result_summary_id' field */
    public fr.proline.core.om.model.msi.serializer.ResultSummary.Builder setDecoyResultSummaryId(int value) {
      validate(fields()[9], value);
      this.decoy_result_summary_id = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'decoy_result_summary_id' field has been set */
    public boolean hasDecoyResultSummaryId() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'decoy_result_summary_id' field */
    public fr.proline.core.om.model.msi.serializer.ResultSummary.Builder clearDecoyResultSummaryId() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'children_ids' field */
    public java.util.List<java.lang.Integer> getChildrenIds() {
      return children_ids;
    }
    
    /** Sets the value of the 'children_ids' field */
    public fr.proline.core.om.model.msi.serializer.ResultSummary.Builder setChildrenIds(java.util.List<java.lang.Integer> value) {
      validate(fields()[10], value);
      this.children_ids = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'children_ids' field has been set */
    public boolean hasChildrenIds() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'children_ids' field */
    public fr.proline.core.om.model.msi.serializer.ResultSummary.Builder clearChildrenIds() {
      children_ids = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    @Override
    public ResultSummary build() {
      try {
        ResultSummary record = new ResultSummary();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.description = fieldSetFlags()[1] ? this.description : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.is_decoy = fieldSetFlags()[2] ? this.is_decoy : (java.lang.Boolean) defaultValue(fields()[2]);
        record.is_quantified = fieldSetFlags()[3] ? this.is_quantified : (java.lang.Boolean) defaultValue(fields()[3]);
        record.modification_timestamp = fieldSetFlags()[4] ? this.modification_timestamp : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.peptide_sets = fieldSetFlags()[5] ? this.peptide_sets : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[5]);
        record.protein_sets = fieldSetFlags()[6] ? this.protein_sets : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[6]);
        record.properties = fieldSetFlags()[7] ? this.properties : (fr.proline.core.om.model.msi.serializer.ResultSummaryProperties) defaultValue(fields()[7]);
        record.result_set_id = fieldSetFlags()[8] ? this.result_set_id : (java.lang.Integer) defaultValue(fields()[8]);
        record.decoy_result_summary_id = fieldSetFlags()[9] ? this.decoy_result_summary_id : (java.lang.Integer) defaultValue(fields()[9]);
        record.children_ids = fieldSetFlags()[10] ? this.children_ids : (java.util.List<java.lang.Integer>) defaultValue(fields()[10]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
