/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package fr.proline.core.om.model.msi.serializer;  
@SuppressWarnings("all")
public class SearchSettings extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SearchSettings\",\"namespace\":\"fr.proline.core.om.model.msi.serializer\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"software_name\",\"type\":\"string\"},{\"name\":\"software_version\",\"type\":\"string\"},{\"name\":\"taxonomy\",\"type\":\"string\"},{\"name\":\"max_missed_cleavages\",\"type\":\"int\"},{\"name\":\"ms1_charge_states\",\"type\":\"string\"},{\"name\":\"ms1_mass_error_tolerance\",\"type\":\"double\"},{\"name\":\"ms1_mass_error_tolerance_unit\",\"type\":\"string\"},{\"name\":\"is_decoy\",\"type\":\"boolean\"},{\"name\":\"used_enzymes\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"variable_ptm_defs\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"fixed_ptm_defs\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"seq_databases\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"instrument_config\",\"type\":{\"type\":\"record\",\"name\":\"InstrumentConfig\",\"fields\":[{\"name\":\"id\",\"type\":\"int\",\"default\":\"\"},{\"name\":\"name\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"instrument\",\"type\":{\"type\":\"record\",\"name\":\"Instrument\",\"fields\":[{\"name\":\"id\",\"type\":\"int\",\"default\":\"\"},{\"name\":\"name\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"source\",\"type\":\"string\"}]}},{\"name\":\"ms1_analyzer\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"msn_analyzer\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"activation_type\",\"type\":\"string\",\"default\":\"\"}]}},{\"name\":\"quantitation\",\"type\":\"string\"}]}");
  @Deprecated public int id;
  @Deprecated public java.lang.CharSequence software_name;
  @Deprecated public java.lang.CharSequence software_version;
  @Deprecated public java.lang.CharSequence taxonomy;
  @Deprecated public int max_missed_cleavages;
  @Deprecated public java.lang.CharSequence ms1_charge_states;
  @Deprecated public double ms1_mass_error_tolerance;
  @Deprecated public java.lang.CharSequence ms1_mass_error_tolerance_unit;
  @Deprecated public boolean is_decoy;
  @Deprecated public java.util.List<java.lang.CharSequence> used_enzymes;
  @Deprecated public java.util.List<java.lang.CharSequence> variable_ptm_defs;
  @Deprecated public java.util.List<java.lang.CharSequence> fixed_ptm_defs;
  @Deprecated public java.util.List<java.lang.CharSequence> seq_databases;
  @Deprecated public fr.proline.core.om.model.msi.serializer.InstrumentConfig instrument_config;
  @Deprecated public java.lang.CharSequence quantitation;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return software_name;
    case 2: return software_version;
    case 3: return taxonomy;
    case 4: return max_missed_cleavages;
    case 5: return ms1_charge_states;
    case 6: return ms1_mass_error_tolerance;
    case 7: return ms1_mass_error_tolerance_unit;
    case 8: return is_decoy;
    case 9: return used_enzymes;
    case 10: return variable_ptm_defs;
    case 11: return fixed_ptm_defs;
    case 12: return seq_databases;
    case 13: return instrument_config;
    case 14: return quantitation;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: software_name = (java.lang.CharSequence)value$; break;
    case 2: software_version = (java.lang.CharSequence)value$; break;
    case 3: taxonomy = (java.lang.CharSequence)value$; break;
    case 4: max_missed_cleavages = (java.lang.Integer)value$; break;
    case 5: ms1_charge_states = (java.lang.CharSequence)value$; break;
    case 6: ms1_mass_error_tolerance = (java.lang.Double)value$; break;
    case 7: ms1_mass_error_tolerance_unit = (java.lang.CharSequence)value$; break;
    case 8: is_decoy = (java.lang.Boolean)value$; break;
    case 9: used_enzymes = (java.util.List<java.lang.CharSequence>)value$; break;
    case 10: variable_ptm_defs = (java.util.List<java.lang.CharSequence>)value$; break;
    case 11: fixed_ptm_defs = (java.util.List<java.lang.CharSequence>)value$; break;
    case 12: seq_databases = (java.util.List<java.lang.CharSequence>)value$; break;
    case 13: instrument_config = (fr.proline.core.om.model.msi.serializer.InstrumentConfig)value$; break;
    case 14: quantitation = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'software_name' field.
   */
  public java.lang.CharSequence getSoftwareName() {
    return software_name;
  }

  /**
   * Sets the value of the 'software_name' field.
   * @param value the value to set.
   */
  public void setSoftwareName(java.lang.CharSequence value) {
    this.software_name = value;
  }

  /**
   * Gets the value of the 'software_version' field.
   */
  public java.lang.CharSequence getSoftwareVersion() {
    return software_version;
  }

  /**
   * Sets the value of the 'software_version' field.
   * @param value the value to set.
   */
  public void setSoftwareVersion(java.lang.CharSequence value) {
    this.software_version = value;
  }

  /**
   * Gets the value of the 'taxonomy' field.
   */
  public java.lang.CharSequence getTaxonomy() {
    return taxonomy;
  }

  /**
   * Sets the value of the 'taxonomy' field.
   * @param value the value to set.
   */
  public void setTaxonomy(java.lang.CharSequence value) {
    this.taxonomy = value;
  }

  /**
   * Gets the value of the 'max_missed_cleavages' field.
   */
  public java.lang.Integer getMaxMissedCleavages() {
    return max_missed_cleavages;
  }

  /**
   * Sets the value of the 'max_missed_cleavages' field.
   * @param value the value to set.
   */
  public void setMaxMissedCleavages(java.lang.Integer value) {
    this.max_missed_cleavages = value;
  }

  /**
   * Gets the value of the 'ms1_charge_states' field.
   */
  public java.lang.CharSequence getMs1ChargeStates() {
    return ms1_charge_states;
  }

  /**
   * Sets the value of the 'ms1_charge_states' field.
   * @param value the value to set.
   */
  public void setMs1ChargeStates(java.lang.CharSequence value) {
    this.ms1_charge_states = value;
  }

  /**
   * Gets the value of the 'ms1_mass_error_tolerance' field.
   */
  public java.lang.Double getMs1MassErrorTolerance() {
    return ms1_mass_error_tolerance;
  }

  /**
   * Sets the value of the 'ms1_mass_error_tolerance' field.
   * @param value the value to set.
   */
  public void setMs1MassErrorTolerance(java.lang.Double value) {
    this.ms1_mass_error_tolerance = value;
  }

  /**
   * Gets the value of the 'ms1_mass_error_tolerance_unit' field.
   */
  public java.lang.CharSequence getMs1MassErrorToleranceUnit() {
    return ms1_mass_error_tolerance_unit;
  }

  /**
   * Sets the value of the 'ms1_mass_error_tolerance_unit' field.
   * @param value the value to set.
   */
  public void setMs1MassErrorToleranceUnit(java.lang.CharSequence value) {
    this.ms1_mass_error_tolerance_unit = value;
  }

  /**
   * Gets the value of the 'is_decoy' field.
   */
  public java.lang.Boolean getIsDecoy() {
    return is_decoy;
  }

  /**
   * Sets the value of the 'is_decoy' field.
   * @param value the value to set.
   */
  public void setIsDecoy(java.lang.Boolean value) {
    this.is_decoy = value;
  }

  /**
   * Gets the value of the 'used_enzymes' field.
   */
  public java.util.List<java.lang.CharSequence> getUsedEnzymes() {
    return used_enzymes;
  }

  /**
   * Sets the value of the 'used_enzymes' field.
   * @param value the value to set.
   */
  public void setUsedEnzymes(java.util.List<java.lang.CharSequence> value) {
    this.used_enzymes = value;
  }

  /**
   * Gets the value of the 'variable_ptm_defs' field.
   */
  public java.util.List<java.lang.CharSequence> getVariablePtmDefs() {
    return variable_ptm_defs;
  }

  /**
   * Sets the value of the 'variable_ptm_defs' field.
   * @param value the value to set.
   */
  public void setVariablePtmDefs(java.util.List<java.lang.CharSequence> value) {
    this.variable_ptm_defs = value;
  }

  /**
   * Gets the value of the 'fixed_ptm_defs' field.
   */
  public java.util.List<java.lang.CharSequence> getFixedPtmDefs() {
    return fixed_ptm_defs;
  }

  /**
   * Sets the value of the 'fixed_ptm_defs' field.
   * @param value the value to set.
   */
  public void setFixedPtmDefs(java.util.List<java.lang.CharSequence> value) {
    this.fixed_ptm_defs = value;
  }

  /**
   * Gets the value of the 'seq_databases' field.
   */
  public java.util.List<java.lang.CharSequence> getSeqDatabases() {
    return seq_databases;
  }

  /**
   * Sets the value of the 'seq_databases' field.
   * @param value the value to set.
   */
  public void setSeqDatabases(java.util.List<java.lang.CharSequence> value) {
    this.seq_databases = value;
  }

  /**
   * Gets the value of the 'instrument_config' field.
   */
  public fr.proline.core.om.model.msi.serializer.InstrumentConfig getInstrumentConfig() {
    return instrument_config;
  }

  /**
   * Sets the value of the 'instrument_config' field.
   * @param value the value to set.
   */
  public void setInstrumentConfig(fr.proline.core.om.model.msi.serializer.InstrumentConfig value) {
    this.instrument_config = value;
  }

  /**
   * Gets the value of the 'quantitation' field.
   */
  public java.lang.CharSequence getQuantitation() {
    return quantitation;
  }

  /**
   * Sets the value of the 'quantitation' field.
   * @param value the value to set.
   */
  public void setQuantitation(java.lang.CharSequence value) {
    this.quantitation = value;
  }

  /** Creates a new SearchSettings RecordBuilder */
  public static fr.proline.core.om.model.msi.serializer.SearchSettings.Builder newBuilder() {
    return new fr.proline.core.om.model.msi.serializer.SearchSettings.Builder();
  }
  
  /** Creates a new SearchSettings RecordBuilder by copying an existing Builder */
  public static fr.proline.core.om.model.msi.serializer.SearchSettings.Builder newBuilder(fr.proline.core.om.model.msi.serializer.SearchSettings.Builder other) {
    return new fr.proline.core.om.model.msi.serializer.SearchSettings.Builder(other);
  }
  
  /** Creates a new SearchSettings RecordBuilder by copying an existing SearchSettings instance */
  public static fr.proline.core.om.model.msi.serializer.SearchSettings.Builder newBuilder(fr.proline.core.om.model.msi.serializer.SearchSettings other) {
    return new fr.proline.core.om.model.msi.serializer.SearchSettings.Builder(other);
  }
  
  /**
   * RecordBuilder for SearchSettings instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SearchSettings>
    implements org.apache.avro.data.RecordBuilder<SearchSettings> {

    private int id;
    private java.lang.CharSequence software_name;
    private java.lang.CharSequence software_version;
    private java.lang.CharSequence taxonomy;
    private int max_missed_cleavages;
    private java.lang.CharSequence ms1_charge_states;
    private double ms1_mass_error_tolerance;
    private java.lang.CharSequence ms1_mass_error_tolerance_unit;
    private boolean is_decoy;
    private java.util.List<java.lang.CharSequence> used_enzymes;
    private java.util.List<java.lang.CharSequence> variable_ptm_defs;
    private java.util.List<java.lang.CharSequence> fixed_ptm_defs;
    private java.util.List<java.lang.CharSequence> seq_databases;
    private fr.proline.core.om.model.msi.serializer.InstrumentConfig instrument_config;
    private java.lang.CharSequence quantitation;

    /** Creates a new Builder */
    private Builder() {
      super(fr.proline.core.om.model.msi.serializer.SearchSettings.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(fr.proline.core.om.model.msi.serializer.SearchSettings.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing SearchSettings instance */
    private Builder(fr.proline.core.om.model.msi.serializer.SearchSettings other) {
            super(fr.proline.core.om.model.msi.serializer.SearchSettings.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = (java.lang.Integer) data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.software_name)) {
        this.software_name = (java.lang.CharSequence) data().deepCopy(fields()[1].schema(), other.software_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.software_version)) {
        this.software_version = (java.lang.CharSequence) data().deepCopy(fields()[2].schema(), other.software_version);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.taxonomy)) {
        this.taxonomy = (java.lang.CharSequence) data().deepCopy(fields()[3].schema(), other.taxonomy);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.max_missed_cleavages)) {
        this.max_missed_cleavages = (java.lang.Integer) data().deepCopy(fields()[4].schema(), other.max_missed_cleavages);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.ms1_charge_states)) {
        this.ms1_charge_states = (java.lang.CharSequence) data().deepCopy(fields()[5].schema(), other.ms1_charge_states);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.ms1_mass_error_tolerance)) {
        this.ms1_mass_error_tolerance = (java.lang.Double) data().deepCopy(fields()[6].schema(), other.ms1_mass_error_tolerance);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.ms1_mass_error_tolerance_unit)) {
        this.ms1_mass_error_tolerance_unit = (java.lang.CharSequence) data().deepCopy(fields()[7].schema(), other.ms1_mass_error_tolerance_unit);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.is_decoy)) {
        this.is_decoy = (java.lang.Boolean) data().deepCopy(fields()[8].schema(), other.is_decoy);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.used_enzymes)) {
        this.used_enzymes = (java.util.List<java.lang.CharSequence>) data().deepCopy(fields()[9].schema(), other.used_enzymes);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.variable_ptm_defs)) {
        this.variable_ptm_defs = (java.util.List<java.lang.CharSequence>) data().deepCopy(fields()[10].schema(), other.variable_ptm_defs);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.fixed_ptm_defs)) {
        this.fixed_ptm_defs = (java.util.List<java.lang.CharSequence>) data().deepCopy(fields()[11].schema(), other.fixed_ptm_defs);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.seq_databases)) {
        this.seq_databases = (java.util.List<java.lang.CharSequence>) data().deepCopy(fields()[12].schema(), other.seq_databases);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.instrument_config)) {
        this.instrument_config = (fr.proline.core.om.model.msi.serializer.InstrumentConfig) data().deepCopy(fields()[13].schema(), other.instrument_config);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.quantitation)) {
        this.quantitation = (java.lang.CharSequence) data().deepCopy(fields()[14].schema(), other.quantitation);
        fieldSetFlags()[14] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.Integer getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'software_name' field */
    public java.lang.CharSequence getSoftwareName() {
      return software_name;
    }
    
    /** Sets the value of the 'software_name' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder setSoftwareName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.software_name = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'software_name' field has been set */
    public boolean hasSoftwareName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'software_name' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder clearSoftwareName() {
      software_name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'software_version' field */
    public java.lang.CharSequence getSoftwareVersion() {
      return software_version;
    }
    
    /** Sets the value of the 'software_version' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder setSoftwareVersion(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.software_version = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'software_version' field has been set */
    public boolean hasSoftwareVersion() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'software_version' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder clearSoftwareVersion() {
      software_version = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'taxonomy' field */
    public java.lang.CharSequence getTaxonomy() {
      return taxonomy;
    }
    
    /** Sets the value of the 'taxonomy' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder setTaxonomy(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.taxonomy = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'taxonomy' field has been set */
    public boolean hasTaxonomy() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'taxonomy' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder clearTaxonomy() {
      taxonomy = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'max_missed_cleavages' field */
    public java.lang.Integer getMaxMissedCleavages() {
      return max_missed_cleavages;
    }
    
    /** Sets the value of the 'max_missed_cleavages' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder setMaxMissedCleavages(int value) {
      validate(fields()[4], value);
      this.max_missed_cleavages = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'max_missed_cleavages' field has been set */
    public boolean hasMaxMissedCleavages() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'max_missed_cleavages' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder clearMaxMissedCleavages() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'ms1_charge_states' field */
    public java.lang.CharSequence getMs1ChargeStates() {
      return ms1_charge_states;
    }
    
    /** Sets the value of the 'ms1_charge_states' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder setMs1ChargeStates(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.ms1_charge_states = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'ms1_charge_states' field has been set */
    public boolean hasMs1ChargeStates() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'ms1_charge_states' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder clearMs1ChargeStates() {
      ms1_charge_states = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'ms1_mass_error_tolerance' field */
    public java.lang.Double getMs1MassErrorTolerance() {
      return ms1_mass_error_tolerance;
    }
    
    /** Sets the value of the 'ms1_mass_error_tolerance' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder setMs1MassErrorTolerance(double value) {
      validate(fields()[6], value);
      this.ms1_mass_error_tolerance = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'ms1_mass_error_tolerance' field has been set */
    public boolean hasMs1MassErrorTolerance() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'ms1_mass_error_tolerance' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder clearMs1MassErrorTolerance() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'ms1_mass_error_tolerance_unit' field */
    public java.lang.CharSequence getMs1MassErrorToleranceUnit() {
      return ms1_mass_error_tolerance_unit;
    }
    
    /** Sets the value of the 'ms1_mass_error_tolerance_unit' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder setMs1MassErrorToleranceUnit(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.ms1_mass_error_tolerance_unit = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'ms1_mass_error_tolerance_unit' field has been set */
    public boolean hasMs1MassErrorToleranceUnit() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'ms1_mass_error_tolerance_unit' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder clearMs1MassErrorToleranceUnit() {
      ms1_mass_error_tolerance_unit = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'is_decoy' field */
    public java.lang.Boolean getIsDecoy() {
      return is_decoy;
    }
    
    /** Sets the value of the 'is_decoy' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder setIsDecoy(boolean value) {
      validate(fields()[8], value);
      this.is_decoy = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'is_decoy' field has been set */
    public boolean hasIsDecoy() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'is_decoy' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder clearIsDecoy() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'used_enzymes' field */
    public java.util.List<java.lang.CharSequence> getUsedEnzymes() {
      return used_enzymes;
    }
    
    /** Sets the value of the 'used_enzymes' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder setUsedEnzymes(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[9], value);
      this.used_enzymes = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'used_enzymes' field has been set */
    public boolean hasUsedEnzymes() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'used_enzymes' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder clearUsedEnzymes() {
      used_enzymes = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'variable_ptm_defs' field */
    public java.util.List<java.lang.CharSequence> getVariablePtmDefs() {
      return variable_ptm_defs;
    }
    
    /** Sets the value of the 'variable_ptm_defs' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder setVariablePtmDefs(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[10], value);
      this.variable_ptm_defs = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'variable_ptm_defs' field has been set */
    public boolean hasVariablePtmDefs() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'variable_ptm_defs' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder clearVariablePtmDefs() {
      variable_ptm_defs = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'fixed_ptm_defs' field */
    public java.util.List<java.lang.CharSequence> getFixedPtmDefs() {
      return fixed_ptm_defs;
    }
    
    /** Sets the value of the 'fixed_ptm_defs' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder setFixedPtmDefs(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[11], value);
      this.fixed_ptm_defs = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'fixed_ptm_defs' field has been set */
    public boolean hasFixedPtmDefs() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'fixed_ptm_defs' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder clearFixedPtmDefs() {
      fixed_ptm_defs = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'seq_databases' field */
    public java.util.List<java.lang.CharSequence> getSeqDatabases() {
      return seq_databases;
    }
    
    /** Sets the value of the 'seq_databases' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder setSeqDatabases(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[12], value);
      this.seq_databases = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'seq_databases' field has been set */
    public boolean hasSeqDatabases() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'seq_databases' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder clearSeqDatabases() {
      seq_databases = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'instrument_config' field */
    public fr.proline.core.om.model.msi.serializer.InstrumentConfig getInstrumentConfig() {
      return instrument_config;
    }
    
    /** Sets the value of the 'instrument_config' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder setInstrumentConfig(fr.proline.core.om.model.msi.serializer.InstrumentConfig value) {
      validate(fields()[13], value);
      this.instrument_config = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'instrument_config' field has been set */
    public boolean hasInstrumentConfig() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'instrument_config' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder clearInstrumentConfig() {
      instrument_config = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'quantitation' field */
    public java.lang.CharSequence getQuantitation() {
      return quantitation;
    }
    
    /** Sets the value of the 'quantitation' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder setQuantitation(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.quantitation = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'quantitation' field has been set */
    public boolean hasQuantitation() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'quantitation' field */
    public fr.proline.core.om.model.msi.serializer.SearchSettings.Builder clearQuantitation() {
      quantitation = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    @Override
    public SearchSettings build() {
      try {
        SearchSettings record = new SearchSettings();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.software_name = fieldSetFlags()[1] ? this.software_name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.software_version = fieldSetFlags()[2] ? this.software_version : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.taxonomy = fieldSetFlags()[3] ? this.taxonomy : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.max_missed_cleavages = fieldSetFlags()[4] ? this.max_missed_cleavages : (java.lang.Integer) defaultValue(fields()[4]);
        record.ms1_charge_states = fieldSetFlags()[5] ? this.ms1_charge_states : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.ms1_mass_error_tolerance = fieldSetFlags()[6] ? this.ms1_mass_error_tolerance : (java.lang.Double) defaultValue(fields()[6]);
        record.ms1_mass_error_tolerance_unit = fieldSetFlags()[7] ? this.ms1_mass_error_tolerance_unit : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.is_decoy = fieldSetFlags()[8] ? this.is_decoy : (java.lang.Boolean) defaultValue(fields()[8]);
        record.used_enzymes = fieldSetFlags()[9] ? this.used_enzymes : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[9]);
        record.variable_ptm_defs = fieldSetFlags()[10] ? this.variable_ptm_defs : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[10]);
        record.fixed_ptm_defs = fieldSetFlags()[11] ? this.fixed_ptm_defs : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[11]);
        record.seq_databases = fieldSetFlags()[12] ? this.seq_databases : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[12]);
        record.instrument_config = fieldSetFlags()[13] ? this.instrument_config : (fr.proline.core.om.model.msi.serializer.InstrumentConfig) defaultValue(fields()[13]);
        record.quantitation = fieldSetFlags()[14] ? this.quantitation : (java.lang.CharSequence) defaultValue(fields()[14]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
