/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package fr.proline.core.om.model.msi.serializer;  
@SuppressWarnings("all")
public class Spectrum extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Spectrum\",\"namespace\":\"fr.proline.core.om.model.msi.serializer\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"title\",\"type\":\"string\"},{\"name\":\"precursor_moz\",\"type\":\"double\"},{\"name\":\"precursor_intensity\",\"type\":\"float\"},{\"name\":\"precursor_charge\",\"type\":\"int\"},{\"name\":\"is_summed\",\"type\":\"boolean\"},{\"name\":\"first_cycle\",\"type\":\"int\"},{\"name\":\"last_cycle\",\"type\":\"int\"},{\"name\":\"first_scan\",\"type\":\"int\"},{\"name\":\"last_scan\",\"type\":\"int\"},{\"name\":\"first_time\",\"type\":\"float\"},{\"name\":\"last_time\",\"type\":\"float\"},{\"name\":\"moz_list\",\"type\":{\"type\":\"array\",\"items\":\"double\"}},{\"name\":\"intensity_list\",\"type\":{\"type\":\"array\",\"items\":\"double\"}},{\"name\":\"peaks_count\",\"type\":\"int\"},{\"name\":\"instrument_config_id\",\"type\":\"int\"},{\"name\":\"peaklist_id\",\"type\":\"int\"}]}");
  @Deprecated public int id;
  @Deprecated public java.lang.CharSequence title;
  @Deprecated public double precursor_moz;
  @Deprecated public float precursor_intensity;
  @Deprecated public int precursor_charge;
  @Deprecated public boolean is_summed;
  @Deprecated public int first_cycle;
  @Deprecated public int last_cycle;
  @Deprecated public int first_scan;
  @Deprecated public int last_scan;
  @Deprecated public float first_time;
  @Deprecated public float last_time;
  @Deprecated public java.util.List<java.lang.Double> moz_list;
  @Deprecated public java.util.List<java.lang.Double> intensity_list;
  @Deprecated public int peaks_count;
  @Deprecated public int instrument_config_id;
  @Deprecated public int peaklist_id;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return title;
    case 2: return precursor_moz;
    case 3: return precursor_intensity;
    case 4: return precursor_charge;
    case 5: return is_summed;
    case 6: return first_cycle;
    case 7: return last_cycle;
    case 8: return first_scan;
    case 9: return last_scan;
    case 10: return first_time;
    case 11: return last_time;
    case 12: return moz_list;
    case 13: return intensity_list;
    case 14: return peaks_count;
    case 15: return instrument_config_id;
    case 16: return peaklist_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: title = (java.lang.CharSequence)value$; break;
    case 2: precursor_moz = (java.lang.Double)value$; break;
    case 3: precursor_intensity = (java.lang.Float)value$; break;
    case 4: precursor_charge = (java.lang.Integer)value$; break;
    case 5: is_summed = (java.lang.Boolean)value$; break;
    case 6: first_cycle = (java.lang.Integer)value$; break;
    case 7: last_cycle = (java.lang.Integer)value$; break;
    case 8: first_scan = (java.lang.Integer)value$; break;
    case 9: last_scan = (java.lang.Integer)value$; break;
    case 10: first_time = (java.lang.Float)value$; break;
    case 11: last_time = (java.lang.Float)value$; break;
    case 12: moz_list = (java.util.List<java.lang.Double>)value$; break;
    case 13: intensity_list = (java.util.List<java.lang.Double>)value$; break;
    case 14: peaks_count = (java.lang.Integer)value$; break;
    case 15: instrument_config_id = (java.lang.Integer)value$; break;
    case 16: peaklist_id = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }

  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'precursor_moz' field.
   */
  public java.lang.Double getPrecursorMoz() {
    return precursor_moz;
  }

  /**
   * Sets the value of the 'precursor_moz' field.
   * @param value the value to set.
   */
  public void setPrecursorMoz(java.lang.Double value) {
    this.precursor_moz = value;
  }

  /**
   * Gets the value of the 'precursor_intensity' field.
   */
  public java.lang.Float getPrecursorIntensity() {
    return precursor_intensity;
  }

  /**
   * Sets the value of the 'precursor_intensity' field.
   * @param value the value to set.
   */
  public void setPrecursorIntensity(java.lang.Float value) {
    this.precursor_intensity = value;
  }

  /**
   * Gets the value of the 'precursor_charge' field.
   */
  public java.lang.Integer getPrecursorCharge() {
    return precursor_charge;
  }

  /**
   * Sets the value of the 'precursor_charge' field.
   * @param value the value to set.
   */
  public void setPrecursorCharge(java.lang.Integer value) {
    this.precursor_charge = value;
  }

  /**
   * Gets the value of the 'is_summed' field.
   */
  public java.lang.Boolean getIsSummed() {
    return is_summed;
  }

  /**
   * Sets the value of the 'is_summed' field.
   * @param value the value to set.
   */
  public void setIsSummed(java.lang.Boolean value) {
    this.is_summed = value;
  }

  /**
   * Gets the value of the 'first_cycle' field.
   */
  public java.lang.Integer getFirstCycle() {
    return first_cycle;
  }

  /**
   * Sets the value of the 'first_cycle' field.
   * @param value the value to set.
   */
  public void setFirstCycle(java.lang.Integer value) {
    this.first_cycle = value;
  }

  /**
   * Gets the value of the 'last_cycle' field.
   */
  public java.lang.Integer getLastCycle() {
    return last_cycle;
  }

  /**
   * Sets the value of the 'last_cycle' field.
   * @param value the value to set.
   */
  public void setLastCycle(java.lang.Integer value) {
    this.last_cycle = value;
  }

  /**
   * Gets the value of the 'first_scan' field.
   */
  public java.lang.Integer getFirstScan() {
    return first_scan;
  }

  /**
   * Sets the value of the 'first_scan' field.
   * @param value the value to set.
   */
  public void setFirstScan(java.lang.Integer value) {
    this.first_scan = value;
  }

  /**
   * Gets the value of the 'last_scan' field.
   */
  public java.lang.Integer getLastScan() {
    return last_scan;
  }

  /**
   * Sets the value of the 'last_scan' field.
   * @param value the value to set.
   */
  public void setLastScan(java.lang.Integer value) {
    this.last_scan = value;
  }

  /**
   * Gets the value of the 'first_time' field.
   */
  public java.lang.Float getFirstTime() {
    return first_time;
  }

  /**
   * Sets the value of the 'first_time' field.
   * @param value the value to set.
   */
  public void setFirstTime(java.lang.Float value) {
    this.first_time = value;
  }

  /**
   * Gets the value of the 'last_time' field.
   */
  public java.lang.Float getLastTime() {
    return last_time;
  }

  /**
   * Sets the value of the 'last_time' field.
   * @param value the value to set.
   */
  public void setLastTime(java.lang.Float value) {
    this.last_time = value;
  }

  /**
   * Gets the value of the 'moz_list' field.
   */
  public java.util.List<java.lang.Double> getMozList() {
    return moz_list;
  }

  /**
   * Sets the value of the 'moz_list' field.
   * @param value the value to set.
   */
  public void setMozList(java.util.List<java.lang.Double> value) {
    this.moz_list = value;
  }

  /**
   * Gets the value of the 'intensity_list' field.
   */
  public java.util.List<java.lang.Double> getIntensityList() {
    return intensity_list;
  }

  /**
   * Sets the value of the 'intensity_list' field.
   * @param value the value to set.
   */
  public void setIntensityList(java.util.List<java.lang.Double> value) {
    this.intensity_list = value;
  }

  /**
   * Gets the value of the 'peaks_count' field.
   */
  public java.lang.Integer getPeaksCount() {
    return peaks_count;
  }

  /**
   * Sets the value of the 'peaks_count' field.
   * @param value the value to set.
   */
  public void setPeaksCount(java.lang.Integer value) {
    this.peaks_count = value;
  }

  /**
   * Gets the value of the 'instrument_config_id' field.
   */
  public java.lang.Integer getInstrumentConfigId() {
    return instrument_config_id;
  }

  /**
   * Sets the value of the 'instrument_config_id' field.
   * @param value the value to set.
   */
  public void setInstrumentConfigId(java.lang.Integer value) {
    this.instrument_config_id = value;
  }

  /**
   * Gets the value of the 'peaklist_id' field.
   */
  public java.lang.Integer getPeaklistId() {
    return peaklist_id;
  }

  /**
   * Sets the value of the 'peaklist_id' field.
   * @param value the value to set.
   */
  public void setPeaklistId(java.lang.Integer value) {
    this.peaklist_id = value;
  }

  /** Creates a new Spectrum RecordBuilder */
  public static fr.proline.core.om.model.msi.serializer.Spectrum.Builder newBuilder() {
    return new fr.proline.core.om.model.msi.serializer.Spectrum.Builder();
  }
  
  /** Creates a new Spectrum RecordBuilder by copying an existing Builder */
  public static fr.proline.core.om.model.msi.serializer.Spectrum.Builder newBuilder(fr.proline.core.om.model.msi.serializer.Spectrum.Builder other) {
    return new fr.proline.core.om.model.msi.serializer.Spectrum.Builder(other);
  }
  
  /** Creates a new Spectrum RecordBuilder by copying an existing Spectrum instance */
  public static fr.proline.core.om.model.msi.serializer.Spectrum.Builder newBuilder(fr.proline.core.om.model.msi.serializer.Spectrum other) {
    return new fr.proline.core.om.model.msi.serializer.Spectrum.Builder(other);
  }
  
  /**
   * RecordBuilder for Spectrum instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Spectrum>
    implements org.apache.avro.data.RecordBuilder<Spectrum> {

    private int id;
    private java.lang.CharSequence title;
    private double precursor_moz;
    private float precursor_intensity;
    private int precursor_charge;
    private boolean is_summed;
    private int first_cycle;
    private int last_cycle;
    private int first_scan;
    private int last_scan;
    private float first_time;
    private float last_time;
    private java.util.List<java.lang.Double> moz_list;
    private java.util.List<java.lang.Double> intensity_list;
    private int peaks_count;
    private int instrument_config_id;
    private int peaklist_id;

    /** Creates a new Builder */
    private Builder() {
      super(fr.proline.core.om.model.msi.serializer.Spectrum.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(fr.proline.core.om.model.msi.serializer.Spectrum.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Spectrum instance */
    private Builder(fr.proline.core.om.model.msi.serializer.Spectrum other) {
            super(fr.proline.core.om.model.msi.serializer.Spectrum.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = (java.lang.Integer) data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = (java.lang.CharSequence) data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.precursor_moz)) {
        this.precursor_moz = (java.lang.Double) data().deepCopy(fields()[2].schema(), other.precursor_moz);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.precursor_intensity)) {
        this.precursor_intensity = (java.lang.Float) data().deepCopy(fields()[3].schema(), other.precursor_intensity);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.precursor_charge)) {
        this.precursor_charge = (java.lang.Integer) data().deepCopy(fields()[4].schema(), other.precursor_charge);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.is_summed)) {
        this.is_summed = (java.lang.Boolean) data().deepCopy(fields()[5].schema(), other.is_summed);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.first_cycle)) {
        this.first_cycle = (java.lang.Integer) data().deepCopy(fields()[6].schema(), other.first_cycle);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.last_cycle)) {
        this.last_cycle = (java.lang.Integer) data().deepCopy(fields()[7].schema(), other.last_cycle);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.first_scan)) {
        this.first_scan = (java.lang.Integer) data().deepCopy(fields()[8].schema(), other.first_scan);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.last_scan)) {
        this.last_scan = (java.lang.Integer) data().deepCopy(fields()[9].schema(), other.last_scan);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.first_time)) {
        this.first_time = (java.lang.Float) data().deepCopy(fields()[10].schema(), other.first_time);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.last_time)) {
        this.last_time = (java.lang.Float) data().deepCopy(fields()[11].schema(), other.last_time);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.moz_list)) {
        this.moz_list = (java.util.List<java.lang.Double>) data().deepCopy(fields()[12].schema(), other.moz_list);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.intensity_list)) {
        this.intensity_list = (java.util.List<java.lang.Double>) data().deepCopy(fields()[13].schema(), other.intensity_list);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.peaks_count)) {
        this.peaks_count = (java.lang.Integer) data().deepCopy(fields()[14].schema(), other.peaks_count);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.instrument_config_id)) {
        this.instrument_config_id = (java.lang.Integer) data().deepCopy(fields()[15].schema(), other.instrument_config_id);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.peaklist_id)) {
        this.peaklist_id = (java.lang.Integer) data().deepCopy(fields()[16].schema(), other.peaklist_id);
        fieldSetFlags()[16] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.Integer getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'title' field */
    public java.lang.CharSequence getTitle() {
      return title;
    }
    
    /** Sets the value of the 'title' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.title = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'title' field has been set */
    public boolean hasTitle() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'title' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder clearTitle() {
      title = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'precursor_moz' field */
    public java.lang.Double getPrecursorMoz() {
      return precursor_moz;
    }
    
    /** Sets the value of the 'precursor_moz' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder setPrecursorMoz(double value) {
      validate(fields()[2], value);
      this.precursor_moz = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'precursor_moz' field has been set */
    public boolean hasPrecursorMoz() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'precursor_moz' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder clearPrecursorMoz() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'precursor_intensity' field */
    public java.lang.Float getPrecursorIntensity() {
      return precursor_intensity;
    }
    
    /** Sets the value of the 'precursor_intensity' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder setPrecursorIntensity(float value) {
      validate(fields()[3], value);
      this.precursor_intensity = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'precursor_intensity' field has been set */
    public boolean hasPrecursorIntensity() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'precursor_intensity' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder clearPrecursorIntensity() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'precursor_charge' field */
    public java.lang.Integer getPrecursorCharge() {
      return precursor_charge;
    }
    
    /** Sets the value of the 'precursor_charge' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder setPrecursorCharge(int value) {
      validate(fields()[4], value);
      this.precursor_charge = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'precursor_charge' field has been set */
    public boolean hasPrecursorCharge() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'precursor_charge' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder clearPrecursorCharge() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'is_summed' field */
    public java.lang.Boolean getIsSummed() {
      return is_summed;
    }
    
    /** Sets the value of the 'is_summed' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder setIsSummed(boolean value) {
      validate(fields()[5], value);
      this.is_summed = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'is_summed' field has been set */
    public boolean hasIsSummed() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'is_summed' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder clearIsSummed() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'first_cycle' field */
    public java.lang.Integer getFirstCycle() {
      return first_cycle;
    }
    
    /** Sets the value of the 'first_cycle' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder setFirstCycle(int value) {
      validate(fields()[6], value);
      this.first_cycle = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'first_cycle' field has been set */
    public boolean hasFirstCycle() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'first_cycle' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder clearFirstCycle() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'last_cycle' field */
    public java.lang.Integer getLastCycle() {
      return last_cycle;
    }
    
    /** Sets the value of the 'last_cycle' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder setLastCycle(int value) {
      validate(fields()[7], value);
      this.last_cycle = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'last_cycle' field has been set */
    public boolean hasLastCycle() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'last_cycle' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder clearLastCycle() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'first_scan' field */
    public java.lang.Integer getFirstScan() {
      return first_scan;
    }
    
    /** Sets the value of the 'first_scan' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder setFirstScan(int value) {
      validate(fields()[8], value);
      this.first_scan = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'first_scan' field has been set */
    public boolean hasFirstScan() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'first_scan' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder clearFirstScan() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'last_scan' field */
    public java.lang.Integer getLastScan() {
      return last_scan;
    }
    
    /** Sets the value of the 'last_scan' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder setLastScan(int value) {
      validate(fields()[9], value);
      this.last_scan = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'last_scan' field has been set */
    public boolean hasLastScan() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'last_scan' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder clearLastScan() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'first_time' field */
    public java.lang.Float getFirstTime() {
      return first_time;
    }
    
    /** Sets the value of the 'first_time' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder setFirstTime(float value) {
      validate(fields()[10], value);
      this.first_time = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'first_time' field has been set */
    public boolean hasFirstTime() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'first_time' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder clearFirstTime() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'last_time' field */
    public java.lang.Float getLastTime() {
      return last_time;
    }
    
    /** Sets the value of the 'last_time' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder setLastTime(float value) {
      validate(fields()[11], value);
      this.last_time = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'last_time' field has been set */
    public boolean hasLastTime() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'last_time' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder clearLastTime() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'moz_list' field */
    public java.util.List<java.lang.Double> getMozList() {
      return moz_list;
    }
    
    /** Sets the value of the 'moz_list' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder setMozList(java.util.List<java.lang.Double> value) {
      validate(fields()[12], value);
      this.moz_list = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'moz_list' field has been set */
    public boolean hasMozList() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'moz_list' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder clearMozList() {
      moz_list = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'intensity_list' field */
    public java.util.List<java.lang.Double> getIntensityList() {
      return intensity_list;
    }
    
    /** Sets the value of the 'intensity_list' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder setIntensityList(java.util.List<java.lang.Double> value) {
      validate(fields()[13], value);
      this.intensity_list = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'intensity_list' field has been set */
    public boolean hasIntensityList() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'intensity_list' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder clearIntensityList() {
      intensity_list = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'peaks_count' field */
    public java.lang.Integer getPeaksCount() {
      return peaks_count;
    }
    
    /** Sets the value of the 'peaks_count' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder setPeaksCount(int value) {
      validate(fields()[14], value);
      this.peaks_count = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'peaks_count' field has been set */
    public boolean hasPeaksCount() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'peaks_count' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder clearPeaksCount() {
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'instrument_config_id' field */
    public java.lang.Integer getInstrumentConfigId() {
      return instrument_config_id;
    }
    
    /** Sets the value of the 'instrument_config_id' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder setInstrumentConfigId(int value) {
      validate(fields()[15], value);
      this.instrument_config_id = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'instrument_config_id' field has been set */
    public boolean hasInstrumentConfigId() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'instrument_config_id' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder clearInstrumentConfigId() {
      fieldSetFlags()[15] = false;
      return this;
    }

    /** Gets the value of the 'peaklist_id' field */
    public java.lang.Integer getPeaklistId() {
      return peaklist_id;
    }
    
    /** Sets the value of the 'peaklist_id' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder setPeaklistId(int value) {
      validate(fields()[16], value);
      this.peaklist_id = value;
      fieldSetFlags()[16] = true;
      return this; 
    }
    
    /** Checks whether the 'peaklist_id' field has been set */
    public boolean hasPeaklistId() {
      return fieldSetFlags()[16];
    }
    
    /** Clears the value of the 'peaklist_id' field */
    public fr.proline.core.om.model.msi.serializer.Spectrum.Builder clearPeaklistId() {
      fieldSetFlags()[16] = false;
      return this;
    }

    @Override
    public Spectrum build() {
      try {
        Spectrum record = new Spectrum();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.title = fieldSetFlags()[1] ? this.title : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.precursor_moz = fieldSetFlags()[2] ? this.precursor_moz : (java.lang.Double) defaultValue(fields()[2]);
        record.precursor_intensity = fieldSetFlags()[3] ? this.precursor_intensity : (java.lang.Float) defaultValue(fields()[3]);
        record.precursor_charge = fieldSetFlags()[4] ? this.precursor_charge : (java.lang.Integer) defaultValue(fields()[4]);
        record.is_summed = fieldSetFlags()[5] ? this.is_summed : (java.lang.Boolean) defaultValue(fields()[5]);
        record.first_cycle = fieldSetFlags()[6] ? this.first_cycle : (java.lang.Integer) defaultValue(fields()[6]);
        record.last_cycle = fieldSetFlags()[7] ? this.last_cycle : (java.lang.Integer) defaultValue(fields()[7]);
        record.first_scan = fieldSetFlags()[8] ? this.first_scan : (java.lang.Integer) defaultValue(fields()[8]);
        record.last_scan = fieldSetFlags()[9] ? this.last_scan : (java.lang.Integer) defaultValue(fields()[9]);
        record.first_time = fieldSetFlags()[10] ? this.first_time : (java.lang.Float) defaultValue(fields()[10]);
        record.last_time = fieldSetFlags()[11] ? this.last_time : (java.lang.Float) defaultValue(fields()[11]);
        record.moz_list = fieldSetFlags()[12] ? this.moz_list : (java.util.List<java.lang.Double>) defaultValue(fields()[12]);
        record.intensity_list = fieldSetFlags()[13] ? this.intensity_list : (java.util.List<java.lang.Double>) defaultValue(fields()[13]);
        record.peaks_count = fieldSetFlags()[14] ? this.peaks_count : (java.lang.Integer) defaultValue(fields()[14]);
        record.instrument_config_id = fieldSetFlags()[15] ? this.instrument_config_id : (java.lang.Integer) defaultValue(fields()[15]);
        record.peaklist_id = fieldSetFlags()[16] ? this.peaklist_id : (java.lang.Integer) defaultValue(fields()[16]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
